#include "../include/generate_html.h"
#include <cstdio>
#include <ctime>
#include <algorithm>

bool generateHtml(const std::string& path,
                  const std::vector<std::pair<PacketRecord, PacketInfo>>& packets,
                  int totalScanned, int serverPkts, int clientPkts)
{
    FILE* f = fopen(path.c_str(), "w");
    if (!f) return false;

    int mcPkts = (int)packets.size();
    fprintf(f, R"(<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>mcprotvis Report</title>
<style>
body{font-family:monospace;background:#1e1e2e;color:#cdd6f4;margin:20px}
h1{color:#cba6f7;border-bottom:2px solid #45475a;padding-bottom:8px}
table{border-collapse:collapse;width:100%}
th{background:#313244;color:#89b4fa;padding:8px;text-align:left;position:sticky;top:0}
td{padding:6px 8px;border-bottom:1px solid #313244}
tr:hover{background:#313244}
.s2c{color:#a6e3a1}
.c2s{color:#89b4fa}
.play{color:#cdd6f4}
.login{color:#f9e2af}
.status{color:#94e2d5}
.handshake{color:#f38ba8}
.summary{background:#181825;padding:15px;border-radius:8px;margin:15px 0}
.stat{display:inline-block;margin:0 20px}
.num{color:#fab387;font-weight:bold}
.footer{color:#6c7086;text-align:center;margin-top:30px}
</style>
</head><body>
<h1>mcprotvis — Minecraft Protocol Report</h1>
<div class="summary">
<div class="stat">Scanned: <span class="num">%d</span></div>
<div class="stat">MC packets: <span class="num">%d</span></div>
<div class="stat">Server→Client: <span class="num">%d</span></div>
<div class="stat">Client→Server: <span class="num">%d</span></div>
</div>
<table>
<tr><th>#</th><th>Time</th><th>Dir</th><th>Packet</th><th>ID</th><th>Length</th><th>State</th></tr>
)",
        totalScanned, mcPkts, serverPkts, clientPkts);

    for (size_t i = 0; i < packets.size(); i++) {
        auto& [rec, info] = packets[i];
        const char* dirClass = rec.fromServer ? "s2c" : "c2s";
        const char* dirSym = rec.fromServer ? "\xe2\x97\x80" : "\xe2\x96\xb6";
        const char* stateClass = info.state.c_str();

        double ts = rec.timestamp;
        time_t sec = time_t(ts);
        struct tm* tm = localtime(&sec);
        char tbuf[64];
        strftime(tbuf, sizeof(tbuf), "%H:%M:%S", tm);
        int ms = int((ts - double(sec)) * 1000);

        fprintf(f, "<tr class=\"%s\">"
                "<td>%zu</td>"
                "<td>%s.%03d</td>"
                "<td>%s</td>"
                "<td>%s</td>"
                "<td>0x%02x</td>"
                "<td>%d</td>"
                "<td>%s</td>"
                "</tr>\n",
                stateClass,
                i, tbuf, ms, dirSym,
                info.name.c_str(), info.id, info.length, info.state.c_str());
    }

    fprintf(f, "</table>\n<div class=\"footer\">Generated by mcprotvis</div>\n</body></html>\n");
    fclose(f);
    return true;
}
