#include "include/ui_styles.h"
#include <gtk/gtk.h>

namespace ravex {
namespace launcher {
namespace simple {
namespace window {

void apply_css() {
    GtkCssProvider *provider = gtk_css_provider_new();
    const char *css =
        "@keyframes progress-glow {"
        "  0% { background-position: 0% 50%; }"
        "  50% { background-position: 100% 50%; }"
        "  100% { background-position: 0% 50%; }"
        "}"
        "window {"
        "  background: #14141e;"
        "  color: #d0d0d0;"
        "  font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;"
        "}"
        "label {"
        "  font-size: 13px;"
        "  color: #a0a0b0;"
        "}"
        ".header-label {"
        "  font-size: 22px;"
        "  font-weight: 700;"
        "  color: #ffffff;"
        "  margin-top: 6px;"
        "  margin-bottom: 0px;"
        "}"
        ".subtitle-label {"
        "  font-size: 11px;"
        "  color: #707080;"
        "  margin-bottom: 10px;"
        "}"
        "button {"
        "  background: #2a2a3a;"
        "  color: #d0d0d0;"
        "  border: 1px solid #3a3a4e;"
        "  border-radius: 6px;"
        "  padding: 8px 18px;"
        "  font-size: 13px;"
        "  min-width: 100px;"
        "  transition: all 150ms ease;"
        "}"
        "button:hover {"
        "  background: #3a3a4e;"
        "  border-color: #5a5a70;"
        "}"
        "button:active {"
        "  background: #1a1a2a;"
        "}"
        ".launch-btn {"
        "  background: #2d7dd2;"
        "  border: none;"
        "  color: #ffffff;"
        "  font-weight: 600;"
        "  min-width: 130px;"
        "  padding: 10px 24px;"
        "}"
        ".launch-btn:hover {"
        "  background: #3d8de2;"
        "  border: none;"
        "}"
        ".launch-btn:active {"
        "  background: #1d6dc2;"
        "}"
        "combobox {"
        "  background: #1e1e2e;"
        "  color: #d0d0d0;"
        "  border: 1px solid #3a3a4e;"
        "  border-radius: 6px;"
        "  padding: 4px 8px;"
        "}"
        "combobox:hover {"
        "  border-color: #5a5a70;"
        "}"
        "frame {"
        "  border: 1px solid #2a2a3e;"
        "  border-radius: 8px;"
        "  margin-top: 4px;"
        "  background: rgba(20, 20, 30, 0.4);"
        "}"
        "frame > label {"
        "  font-size: 11px;"
        "  color: #707080;"
        "  padding-left: 8px;"
        "}"
        ".inst-label {"
        "  font-size: 13px;"
        "  color: #e0e0e0;"
        "  font-weight: 600;"
        "}"
        ".inst-status {"
        "  font-size: 11px;"
        "  color: #707080;"
        "  font-style: italic;"
        "}"
        "#btn-console {"
        "  background: #2a2a3a;"
        "  border: 1px solid #3a3a4e;"
        "  padding: 4px 14px;"
        "  min-width: 70px;"
        "  font-size: 12px;"
        "  border-radius: 5px;"
        "}"
        "#btn-console:hover {"
        "  background: #3a3a4e;"
        "  border-color: #5a5a70;"
        "}"
        "#btn-kill {"
        "  background: #6b2020;"
        "  border: 1px solid #8a3030;"
        "  padding: 4px 14px;"
        "  min-width: 70px;"
        "  border-radius: 5px;"
        "}"
        "#btn-kill:hover {"
        "  background: #8a3030;"
        "  border-color: #aa4040;"
        "}"
        "#btn-copy {"
        "  padding: 4px 14px;"
        "  border-radius: 5px;"
        "  font-size: 12px;"
        "}"
        "progressbar trough {"
        "  background: #1e1e2e;"
        "  border-radius: 5px;"
        "  border: 1px solid #3a3a4e;"
        "  min-height: 8px;"
        "}"
        "progressbar progress {"
        "  background: linear-gradient(90deg, #2d7dd2, #4a9de8);"
        "  border-radius: 4px;"
        "  min-height: 6px;"
        "  margin: 1px;"
        "  animation: progress-glow 2s ease infinite;"
        "  background-size: 200% 100%;"
        "  transition: width 250ms ease;"
        "}"
        "separator {"
        "  background: #2a2a3e;"
        "  min-height: 1px;"
        "  margin: 3px 0;"
        "}"
        "scrolledwindow {"
        "  border-radius: 6px;"
        "}"
        "textview {"
        "  font-family: 'JetBrains Mono', 'Fira Code', monospace;"
        "  font-size: 10pt;"
        "  background: #0e0e18;"
        "  color: #c0c0c0;"
        "}"
        "textview text {"
        "  background: #0e0e18;"
        "  color: #c0c0c0;"
        "}";

    gtk_css_provider_load_from_data(provider, css, -1, NULL);
    gtk_style_context_add_provider_for_screen(
        gdk_screen_get_default(),
        GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
    );
    g_object_unref(provider);
}

} // namespace window
} // namespace simple
} // namespace launcher
} // namespace ravex
