package ravex.utility.misc;
import java.util.HashMap;
import java.util.Map;
public class LanguageUtility {
    private static String currentLang = "English";
    private static final Map<String, Map<String, String>> STRINGS = new HashMap<>();

    static {
        Map<String, String> en = new HashMap<>();
        en.put("entered", "§f{0} §7entered");
        en.put("left", "§f{0} §7left");
        en.put("pickup", "§f{0} §7pickup §f{1}");
        en.put("ate_gapple", "§f{0} §7ate §eGolden Apple");
        en.put("ate_egapple", "§f{0} §7ate §dEnchanted Golden Apple");
        en.put("drank", "§f{0} §7drank {1}");
        en.put("pop_totem", "§f{0} §7pop §cTotem");
        en.put("shield_broke", "§f{0} §7shield broke");
        en.put("enabled", "Enabled");
        en.put("disabled", "Disabled");
        en.put("has_been", "has been");
        en.put("lag_notify", "Server lag: {0} TPS");
        en.put("lag_recovered", "Server recovered: {0} TPS");
        en.put("durability_own", "Your {0} is at {1}% durability!");
        en.put("durability_own_short", "Own {0}");
        en.put("durability_enemy", "{0}'s {1} is at {2}% durability!");
        en.put("NoEnderChestsLeft", "No ender chests left");
        en.put("NoPickaxeFound", "No pickaxe found");
        en.put("NoChestsInHotbar", "No chests in hotbar");
        en.put("CannotPlaceBlocksInSpectator", "Cannot place blocks in spectator mode");
        en.put("NoSuitablePositionFound", "No suitable position found");
        en.put("NotEnoughSoulSand", "Not enough soul sand");
        en.put("NotEnoughWitherSkeletonSkulls", "Not enough wither skeleton skulls");
        en.put("autowalk_baritone", "§c[AutoWalk] Baritone mod is required for Baritone mode!");
        en.put("quiver_nobow", "§c[Quiver] No bow found in hotbar! Disabling...");
        en.put("quiver_noarrows", "§c[Quiver] No arrows of type {0} found! Disabling...");
        en.put("breaker_sync", "§c[Breaker] PacketMine was disabled, Sync PacketMine turned off!");
        en.put("antpearl_dist", "§ePearl incoming! §f{0}mAway");
        en.put("antpearl", "§ePearl incoming!");
        en.put("elytrahelper_chest", "§c[ElytraHelper] No replacement chest item found!");
        en.put("desktopgui_nolib", "§c[DesktopGui] Native library not found!");
        en.put("fakeplayer_died_respawn", "§8[§cFakePlayer§8] §7Died, respawning");
        en.put("fakeplayer_died", "§8[§cFakePlayer§8] §7Died");
        en.put("antiafk_action", "§aAntiAFK action");
        en.put("search_pick", "§fSelect at least a block or entity in the browser");
        en.put("book_hold", "§eHold a book in main hand");
        en.put("book_updated", "§aBook updated: title=§f{0} §aauthor=§f{1}");
        en.put("book_noread", "§eCould not read book data");
        en.put("book_notitle", "§eProvide a title to sign the book");
        en.put("book_signed", "§aBook signed with title=§f{0}");
        en.put("book_hold_writable", "§eHold a writable or written book in main hand");
        en.put("book_hold_empty", "§eHold a writable book in main hand");
        en.put("book_filled", "§aBook filled with §f{0} §apages");
        en.put("autoportal_obsidian", "Not enough obsidian, disabling");
        en.put("autoportal_frame", "Some frame blocks missing, skipping lighting");
        en.put("holefill_found", "Found {0} hole(s)");
        en.put("holefill_filled", "Filled {0} block(s)");
        en.put("holefill_notenough", "Not enough blocks, disabling");
        en.put("baseplace_placed", "§a[BasePlace] Placed obsidian at §f{0}, {1}, {2}");
        en.put("desc_KillAura", "Attack enemies");
        en.put("desc_mode_Mode_Snap2", "Alternative to Snap (aim at target)");
        en.put("desc_ESP", "See through walls");
        en.put("desc_Search", "Find blocks and entities");
        en.put("desc_AutoTool", "Swap best tool");
        en.put("desc_AntiAfk", "No idle kick");
        en.put("desc_PVEUtils", "Smelt, tame, brew, bone meal & light");
        en.put("desc_ClickGui", "Open menu");
        en.put("desc_Notifications", "Screen alerts");
        en.put("desc_DeathText", "Death message");
        en.put("desc_SoundBlock", "Mute sounds");
        en.put("desc_InvClean", "Clean inventory");
        en.put("desc_Handshake", "Fake handshake");
        en.put("desc_PortalGod", "Portal shield");
        en.put("desc_LiquidControl", "Swim freely");
        en.put("desc_AutoWither", "Build wither");
        en.put("desc_AutoPortal", "Build portals");
        en.put("desc_MainMenu", "Customize main menu");
        en.put("mainmenu_no_gifs", "No GIF files found. Put your .gif files here: {0}");
        en.put("desc_NoBob", "No head bob");
        en.put("desc_Ambient", "Change light");
        en.put("desc_Weather", "Change weather");
        en.put("desc_WorldColor", "World colors");
        en.put("desc_Trails", "Show paths");
        en.put("desc_AspectRatio", "Stretch screen");
        en.put("desc_Waypoint", "Save locations");
        en.put("desc_AimAssist", "Aim helper");
        en.put("desc_NameTags", "Show names");
        en.put("desc_Tracers", "Draw lines");
        en.put("desc_Trigger", "Attack on hover");
        en.put("desc_MaceSwap", "Swap to mace");
        en.put("desc_Hud", "Screen overlay");
        en.put("desc_NoWeb", "Walk through webs");
        en.put("desc_Glint", "Item glow");
        en.put("desc_RichPresence", "Discord status");
        en.put("desc_GuiMove", "Walk in menus");
        en.put("desc_NoSlow", "No slow down");
        en.put("desc_Velocity", "Change knockback");
        en.put("desc_AutoEat", "Eat food");
        en.put("desc_NoInteract", "No misclicks");
        en.put("desc_SourceFiller", "Remove water");
        en.put("desc_AirPlace", "Place in air");
        en.put("desc_Scaffold", "Place bridges");
        en.put("desc_Shaders", "Neon glow");
        en.put("desc_FreeLook", "Free look");
        en.put("desc_FreeCam", "Free camera");
        en.put("desc_ViewClip", "See through blocks");
        en.put("desc_Step", "Step up");
        en.put("desc_ReverseStep", "Pull down");
        en.put("desc_Commands", "Run commands");
        en.put("desc_ItemPhysics", "Item physics");
        en.put("desc_Sounds", "Play sounds");
        en.put("desc_AntiHunger", "No hunger");
        en.put("desc_AutoSign", "Fill signs");
        en.put("desc_AutoShear", "Shear sheep");
        en.put("desc_AutoNameTag", "Name animals");
        en.put("desc_AutoMount", "Ride animals");
        en.put("desc_RideExploit", "Ride anything");
        en.put("desc_AntiVoid", "Void save");
        en.put("desc_AutoMend", "Repair gear");
        en.put("desc_FakePlayer", "Practice dummy");
        en.put("desc_NoDelay", "No delay");
        en.put("desc_AutoRespawn", "Instant respawn");
        en.put("desc_AutoArmor", "Equip armor");
        en.put("desc_FastItem", "Quick item move");
        en.put("desc_LongJump", "Jump far");
        en.put("desc_AutoLog", "Leave fight");
        en.put("desc_WebAura", "Place webs");
        en.put("desc_MaceAura", "Mace smash");
        en.put("desc_AutoTotem", "Swap totems");
        en.put("desc_Hitboxes", "Bigger targets");
        en.put("desc_Sleepy", "Slide around");
        en.put("desc_Reach", "Longer reach");
        en.put("desc_NoPush", "No push");
        en.put("desc_FastBreak", "Break fast");
        en.put("desc_InstaBreak", "Instant break");
        en.put("desc_GhostHand", "Open through walls");
        en.put("desc_AutoSprint", "Always sprint");
        en.put("desc_Spider", "Climb walls");
        en.put("desc_Timer", "Speed up");
        en.put("desc_Speed", "Move fast");
        en.put("desc_Xray", "See ores");
        en.put("desc_Surround", "Protect feet");
        en.put("desc_BlockOutline", "Block highlight");
        en.put("desc_Fullbright", "Always bright");
        en.put("desc_GuiParticles", "Menu sparkles");
        en.put("desc_NoRotate", "No head turn");
        en.put("desc_NoRender", "Hide things");
        en.put("desc_AutoWalk", "Walk forward");
        en.put("desc_MobOwner", "Show owner");
        en.put("desc_SelfTrap", "Trap yourself");
        en.put("desc_WaxAura", "Wax copper");
        en.put("desc_ChestAura", "Place chests");
        en.put("desc_PortalGui", "Use in portals");
        en.put("desc_Avoid", "Avoid damage");
        en.put("desc_TabHelper", "Better list");
        en.put("desc_ChatHelper", "Chat helpers");
        en.put("desc_ChestHelper", "Chest helpers");
        en.put("desc_AutoReconnect", "Rejoin server");
        en.put("desc_FastLatency", "Fast ping");
        en.put("desc_MultiTask", "Do two things");
        en.put("desc_BlockMixer", "Shuffle blocks");
        en.put("desc_AutoSoup", "Drink soup");
        en.put("desc_NameProtect", "Hide names");
        en.put("desc_StashFinder", "Find loot");
        en.put("desc_ClickTP", "Click teleport");
        en.put("desc_ClickFly", "Click to fly");
        en.put("desc_ChorusExploit", "Save teleport");
        en.put("desc_TickShift", "Store bursts");
        en.put("desc_TridentBoost", "Trident boost");
        en.put("desc_WindAura", "Throw wind");
        en.put("desc_BreadCrumbs", "Show trail");
        en.put("desc_ViewModel", "Move hands");
        en.put("desc_AutoCrystal", "Break crystals");
        en.put("desc_Trap", "Trap targets");
        en.put("desc_Igniter", "Light TNT");
        en.put("desc_RidingHelper", "Faster riding");
        en.put("desc_Blink", "Delay moves");
        en.put("desc_PacketFly", "Fly freely");
        en.put("desc_BoatFly", "Fly with boats");
        en.put("desc_AutoApple", "Eat apples");
        en.put("desc_TreeCutter", "Cut trees");
        en.put("desc_FakePearl", "Fake pearl");
        en.put("desc_BasePlace", "Place obsidian");
        en.put("desc_AnchorAura", "Explode anchors");
        en.put("desc_ElytraHelper", "Elytra swap");
        en.put("desc_ViewLock", "Lock view");
        en.put("desc_ItemSaver", "Save items");
        en.put("desc_AntiAim", "Spin head");
        en.put("desc_NoSwing", "No swing");
        en.put("desc_SwingAnimation", "Swing animation");
        en.put("desc_CityESP", "City ESP");
        en.put("desc_DesktopGui", "Desktop control");
        en.put("desc_Breaker", "Break nearby");
        en.put("desc_BowAim", "Aim bow");
        en.put("desc_Quiver", "Shoot arrows");
        en.put("desc_DurabAlert", "Low durability");
        en.put("desc_AntiAttack", "No friendly hits");
        en.put("desc_LagNotify", "Lag warning");
        en.put("desc_PopCounter", "Count totems");
        en.put("desc_BookHelper", "Edit books");
        en.put("desc_WebSelf", "Web yourself");
        en.put("desc_KeyPearl", "Throw pearl");
        en.put("desc_AutoAuth", "Login helper");
        en.put("desc_SafeWalk", "Safe walk");


        en.put("desc_ShieldFucker", "Break shields");
        en.put("desc_KillEffects", "Death effects");
        en.put("desc_AntiQuit", "No leaving");
        en.put("desc_CoordLogger", "Log position");
        en.put("desc_Religion", "Show religions");
        en.put("desc_Phase", "Walk through walls");
        en.put("desc_MineAnimation", "Hide cracks");
        en.put("desc_HighJump", "High jump");
        en.put("desc_FastStairs", "Climb fast");
        en.put("desc_NoFall", "Safe fall");
        en.put("desc_ElytraPlusPlus", "Elytra fly");
        en.put("desc_Flight", "Flip flop nga");
        en.put("desc_Disabler", "Disable everything");
        en.put("desc_Replenish", "Refill items");


        en.put("desc_AutoReplant", "Replant crops");
        en.put("desc_Nuker", "Mass break");
        en.put("desc_AutoTrade", "Trade villagers");
        en.put("desc_AutoFish", "Catch fish");
        en.put("desc_AutoTunnel", "Dig tunnel");


        en.put("desc_ECFarmer", "Farm chests");
        en.put("desc_GhostBlocks", "No fake blocks");
        en.put("desc_AntiPearl", "Pearl warning");
        en.put("desc_BedBomb", "Blow beds");
        en.put("desc_Criticals", "Crit hits");
        en.put("desc_AutoBow", "Release bow");
        en.put("desc_HoleFill", "Fill holes");
        en.put("desc_AutoClicker", "Click fast");
        en.put("desc_AntiBot", "Block bots");
        en.put("desc_AutoDrop", "Drop blocks");

        en.put("desc_Burrow", "Hide in block");
        en.put("desc_PacketMine", "Click mine");
        en.put("desc_PacketHelper", "Network tools");
        en.put("desc_Borders", "Show borders");
        en.put("desc_Zoom", "Camera zoom");
        en.put("desc_Blur", "Blur background");
        en.put("desc_ToolTips", "Item info");
        en.put("desc_ESP_Void", "Show void");
        en.put("desc_AutoReGear", "Refill items");
        en.put("desc_AntiReGear", "Break containers");
        en.put("desc_Skeleton", "Show bodies");
        en.put("desc_ChatHud", "Chat overlay");
        en.put("desc_CooldownsHud", "Show cooldowns");
        en.put("desc_IndicatorsHud", "Target info");
        en.put("desc_InvPreviewHud", "Preview items");
        en.put("desc_MediaHud", "Music info");
        en.put("desc_Settings", "Client settings");
        en.put("desc_TpsHud", "Server speed");
        en.put("desc_Calculator", "Do math");
        en.put("desc_Fonts", "Change fonts");
        en.put("desc_PingSpoof", "Fake ping");
        en.put("desc_ShiftInterp", "Force crouch");
        en.put("desc_SmallUser", "Small players");
        en.put("desc_TntAura", "Bomb targets");
        en.put("desc_Particles", "Pretty particles");
        en.put("desc_Crosshair", "Custom crosshair");
        en.put("desc_PearlTarget", "Track pearls");
        en.put("desc_MiddleClick", "Middle click");
        en.put("desc_Telemetry", "Send data");
        en.put("desc_Baritone", "Find path");
        en.put("desc_PauseBaritone", "Pause path");
        en.put("desc_NewChunks", "New chunks");
        en.put("desc_AutoCart", "Send carts");
        en.put("desc_MessageAura", "Message nearby players");
        en.put("hud_desc_Watermark", "Renders the premium RaveX Client watermark on screen.");
        en.put("hud_desc_ArrayList", "Renders the active (enabled) modules array list.");
        en.put("hud_desc_Coords", "Renders player's current X, Y, Z coordinates.");
        en.put("hud_desc_Fps", "Renders the current game frames per second (FPS) count.");
        en.put("hud_desc_Media", "Shows currently playing music from your system.");
        en.put("hud_desc_Indicators", "Arc gauges for Health, Armor, TPS, Speed, and Knockback.");
        en.put("hud_desc_InvPreview", "Preview of your full inventory and selected hotbar slot.");
        en.put("hud_desc_Chat", "Repositions and scales the in-game chat box.");
        en.put("hud_desc_TPS", "Current server tick rate (TPS) monitor.");
        en.put("hud_desc_Cooldowns", "Displays item cooldowns (Ender Pearl, Chorus, etc.) with remaining percentage.");
        en.put("hud_desc_Currency", "Renders custom live/simulated currency exchange rates for CIS & NATO countries + BTC.");
        en.put("hud_desc_ServerBrand", "Displays the server implementation brand using C++ JNI formatting.");
        en.put("desc_TargetHud", "Target info");
        en.put("hud_desc_TargetHud", "Displays target player statistics, health, armor, and hand items.");
        en.put("hud_editor_scale_hint", "Mouse wheel: scale hovered HUD element");
        en.put("cmd_help", "Help");
        en.put("cmd_config", "Config");
        en.put("cmd_calc", "Calc");
        en.put("cmd_toggle", "Toggle");
        en.put("cmd_bind", "Bind");
        en.put("cmd_panic", "Panic");
        en.put("cmd_say", "Say");
        en.put("cmd_time", "Time");
        en.put("cmd_modules", "Modules");
        en.put("cmd_coords", "Coords");
        en.put("cmd_waypoint", "Waypoint");
        en.put("cmd_friend", "Friend");
        en.put("cmd_plugins", "Plugins");
        en.put("cmd_clear", "Clear");
        en.put("cmd_uuid", "UUID");
        en.put("cmd_nbt", "NBT");
        en.put("gui_tips_title", "Controls");
        en.put("gui_tip_toggle", "Left click - toggle module");
        en.put("gui_tip_settings", "Right click - module settings");
        en.put("gui_tip_bind", "Middle click - set keybind");
        en.put("gui_tip_gear", "Gear - module has settings (ShowGear)");
        en.put("gui_search_placeholder", "Search...");
        en.put("cfg_title", "Configurations");
        en.put("cfg_subtitle", "Manage saved client presets");
        en.put("cfg_saved", "Saved Presets");
        en.put("cfg_empty", "No presets saved yet.");
        en.put("cfg_empty_hint", "Click \"Save New\" below.");
        en.put("cfg_no_selected", "No preset selected");
        en.put("cfg_not_in_world", "Not in a world");
        en.put("cfg_save_new", "Save New");
        en.put("cfg_save", "Save");
        en.put("cfg_load", "Load");
        en.put("cfg_delete", "Delete");
        en.put("cfg_back", "Back");
        en.put("cfg_cancel", "Cancel");
        en.put("cfg_name_hint", "Preset name...");
        en.put("prof_title", "Profile Manager");
        en.put("prof_subtitle", "Save and load module configurations");
        en.put("prof_apply", "Apply");
        en.put("prof_capture", "Capture");
        en.put("prof_refresh", "Refresh");
        en.put("prof_refreshed", "Refreshed");
        en.put("prof_save", "Save");
        en.put("prof_name_hint", "Profile name...");
        en.put("macro_title", "Macro Editor");
        en.put("macro_new", "New Macro");
        en.put("macro_none", "None");
        en.put("macro_press_key", "Press a key...");
        en.put("macro_enter_value", "Enter value...");
        en.put("macro_add_action", "Add Action");
        en.put("macro_delete", "Delete");
        en.put("macro_done", "Done");
        en.put("macro_edit", "Edit");
        en.put("macro_create", "Create");
        en.put("macro_actions", "Actions");
        en.put("macro_cmd", "Execute Command");
        en.put("macro_chat", "Send Chat");
        en.put("macro_toggle", "Toggle Module");
        en.put("hud_editor_title", "RaveX HUD Editor");
        en.put("pal_title", "Color Palette");
        en.put("pal_presets", "Presets");
        en.put("pal_recent", "Recent");
        en.put("pal_rainbow", "Rainbow");
        en.put("pal_positive", "Positive");
        en.put("arg_title", "AutoReGear Kit Editor");
        en.put("arg_subtitle", "AutoReGear Kit Configuration");
        en.put("ic_title", "Inventory Cleaner");
        en.put("ic_quit", "Quit");
        en.put("ob_welcome_title", "Welcome to RaveX");
        en.put("ob_welcome_sub", "A modern utility client for Minecraft. Let's set a few things up.");
        en.put("ob_continue", "Continue");
        en.put("ob_lang_title", "Choose your language");
        en.put("ob_lang_sub", "The whole client will be displayed in this language.");
        en.put("ob_lang_en_name", "English");
        en.put("ob_lang_en_sub", "International");
        en.put("ob_lang_ru_name", "Русский");
        en.put("ob_lang_ru_sub", "Россия");
        en.put("ob_done_title", "You're all set!");
        en.put("ob_done_sub", "Press Enter or click the button to dive in.");
        en.put("ob_enter", "Enter RaveX");
        en.put("ob_skip_hint", "ESC - skip");
        en.put("cfg_selected", "Selected:");
        en.put("cfg_save_as", "Save Preset As:");
        en.put("cfg_auto", "AUTO");
        en.put("cfg_model_slim", "Alex model");
        en.put("cfg_model_wide", "Steve model");
        en.put("prof_save_as", "Save Profile As:");
        en.put("prof_applied", "Profile \"{0}\" applied");
        en.put("prof_deleted", "Profile \"{0}\" deleted");
        en.put("prof_saved", "Profile \"{0}\" saved");
        en.put("macro_subtitle", "Add macros with keybinds that execute multiple actions");
        en.put("macro_empty", "No macros yet. Click \"Create\" to add one.");
        en.put("macro_name", "Name:");
        en.put("macro_editing", "Editing: ");
        en.put("macro_add_action_label", "Add Action:");
        en.put("macro_type", "Type: ");
        en.put("macro_bind", "Bind: ");
        en.put("macro_delay", "Delay (ms)");
        en.put("macro_deleted", "Macro deleted");
        en.put("macro_created", "Macro \"{0}\" created");
        en.put("arg_back", "ESC / Back");
        en.put("arg_save_close", "Save & Close");
        en.put("ic_back", "ESC / Quit");
        en.put("ic_page", "Page {0} / {1}");
        en.put("act_toggle", "Toggle: ");
        en.put("act_chat", "Chat: ");
        en.put("act_cmd", "Cmd: ");
        en.put("act_delay", "Delay: ");
        en.put("act_unknown", "Unknown");
        en.put("gui_title", "RaveX ClickGUI");
        en.put("gui_macros", "Macros");
        en.put("gui_profiles", "Profiles");
        en.put("gui_configs", "Configs");
        en.put("gui_reset", "Reset");
        en.put("gui_hud", "HUD");
        en.put("mb_binding", "Binding");
        en.put("mb_key", "Key ");

        Map<String, String> ru = new HashMap<>();
        ru.put("entered", "§f{0} §7зашёл");
        ru.put("left", "§f{0} §7вышел");
        ru.put("pickup", "§f{0} §7подобрал §f{1}");
        ru.put("ate_gapple", "§f{0} §7съел §eЗолотое Яблоко");
        ru.put("ate_egapple", "§f{0} §7съел §dЗачарованное Золотое Яблоко");
        ru.put("drank", "§f{0} §7выпил {1}");
        ru.put("pop_totem", "§f{0} §7попнул §cТотем");
        ru.put("shield_broke", "§f{0} §7сломал щит");
        ru.put("enabled", "Включен");
        ru.put("disabled", "Выключен");
        ru.put("has_been", "был");
        ru.put("lag_notify", "Лаг сервера: {0} TPS");
        ru.put("lag_recovered", "Сервер восстановился: {0} TPS");
        ru.put("durability_own", "Ваш {0} на {1}% прочности!");
        ru.put("durability_own_short", "Свой {0}");
        ru.put("durability_enemy", "Прочность {1} у {0}: {2}%");
        ru.put("NoEnderChestsLeft", "Эндер-сундуки закончились");
        ru.put("NoPickaxeFound", "Кирка не найдена");
        ru.put("NoChestsInHotbar", "Нет сундуков в хотбаре");
        ru.put("CannotPlaceBlocksInSpectator", "Нельзя ставить блоки в режиме наблюдателя");
        ru.put("NoSuitablePositionFound", "Подходящая позиция не найдена");
        ru.put("NotEnoughSoulSand", "Нехватка песка душ");
        ru.put("NotEnoughWitherSkeletonSkulls", "Нехватка черепов визер-скелетов");
        ru.put("autowalk_baritone", "§c[AutoWalk] Для режима Baritone требуется мод Baritone!");
        ru.put("quiver_nobow", "§c[Quiver] Лук не найден в хотбаре! Отключение...");
        ru.put("quiver_noarrows", "§c[Quiver] Стрелы типа {0} не найдены! Отключение...");
        ru.put("breaker_sync", "§c[Breaker] PacketMine был отключен, Sync PacketMine выключен!");
        ru.put("antpearl_dist", "§eЖемчуг летит! §f{0}м");
        ru.put("antpearl", "§eЖемчуг летит!");
        ru.put("elytrahelper_chest", "§c[ElytraHelper] Запасной нагрудник не найден!");
        ru.put("desktopgui_nolib", "§c[DesktopGui] Нативная библиотека не найдена!");
        ru.put("fakeplayer_died_respawn", "§8[§cFakePlayer§8] §7Умер, возрождение");
        ru.put("fakeplayer_died", "§8[§cFakePlayer§8] §7Умер");
        ru.put("antiafk_action", "§aДействие AntiAFK");
        ru.put("search_pick", "§fВыбери хотя бы блок или энтити в браузере");
        ru.put("book_hold", "§eВозьми книгу в основную руку");
        ru.put("book_updated", "§aКнига обновлена: заголовок=§f{0} §aавтор=§f{1}");
        ru.put("book_noread", "§eНе удалось прочитать данные книги");
        ru.put("book_notitle", "§eУкажи заголовок, чтобы подписать книгу");
        ru.put("book_signed", "§aКнига подписана с заголовком=§f{0}");
        ru.put("book_hold_writable", "§eВозьми книгу для записи или написанную книгу в основную руку");
        ru.put("book_hold_empty", "§eВозьми книгу для записи в основную руку");
        ru.put("book_filled", "§aКнига заполнена §f{0} §aстраницами");
        ru.put("autoportal_obsidian", "Нехватка обсидиана, отключение");
        ru.put("autoportal_frame", "Некоторые блоки рамы отсутствуют, пропускаем поджог");
        ru.put("holefill_found", "Найдено ям: {0}");
        ru.put("holefill_filled", "Заполнено блоков: {0}");
        ru.put("holefill_notenough", "Нехватка блоков, отключение");
        ru.put("baseplace_placed", "§a[BasePlace] Обсидиан установлен на §f{0}, {1}, {2}");
        ru.put("desc_KillAura", "Атака врагов");
        ru.put("desc_mode_Mode_Snap2", "Альтернатива Snap (наводись на цель)");
        ru.put("desc_ESP", "Видеть сквозь стены");
        ru.put("desc_Search", "Поиск блоков и сущностей");
        ru.put("desc_AutoTool", "Автосмена инструмента");
        ru.put("desc_AntiAfk", "Не уходить в AFK");
        ru.put("desc_PVEUtils", "Плавка, приручение, варка, удобрение и свет");
        ru.put("desc_ClickGui", "Открыть меню");
        ru.put("desc_Notifications", "Уведомления на экране");
        ru.put("desc_DeathText", "Кастомный текст смерти");
        ru.put("desc_SoundBlock", "Блокировка звуков");
        ru.put("desc_InvClean", "Очистка инвентаря");
        ru.put("desc_Handshake", "Подмена рукопожатия");
        ru.put("desc_PortalGod", "Неуязвимость в портале");
        ru.put("desc_LiquidControl", "Контроль жидкости");
        ru.put("desc_AutoWither", "Автостройка визера");
        ru.put("desc_AutoPortal", "Автостройка порталов");
        ru.put("desc_MainMenu", "Настройка главного меню");
        ru.put("mainmenu_no_gifs", "GIF-файлы не найдены. Положите .gif файлы сюда: {0}");
        ru.put("desc_NoBob", "Убрать качание головы");
        ru.put("desc_Ambient", "Изменить освещение");
        ru.put("desc_Weather", "Изменить погоду");
        ru.put("desc_WorldColor", "Цвета мира");
        ru.put("desc_Trails", "Показать путь");
        ru.put("desc_AspectRatio", "Растянуть экран");
        ru.put("desc_Waypoint", "Сохранение точек");
        ru.put("desc_AimAssist", "Помощь в прицеле");
        ru.put("desc_NameTags", "Показывать имена");
        ru.put("desc_Tracers", "Линии к игрокам");
        ru.put("desc_Trigger", "Атака при наведении");
        ru.put("desc_MaceSwap", "Свап на булаву");
        ru.put("desc_Hud", "Экранная накладка");
        ru.put("desc_NoWeb", "Ходьба в паутине");
        ru.put("desc_Glint", "Свечение предметов");
        ru.put("desc_RichPresence", "Статус в Discord");
        ru.put("desc_GuiMove", "Ходьба в меню");
        ru.put("desc_NoSlow", "Без замедления");
        ru.put("desc_Velocity", "Изменение отдачи");
        ru.put("desc_AutoEat", "Автоед");
        ru.put("desc_NoInteract", "Без лишних кликов");
        ru.put("desc_SourceFiller", "Убрать воду");
        ru.put("desc_AirPlace", "Ставить в воздухе");
        ru.put("desc_Scaffold", "Автомост");
        ru.put("desc_Shaders", "Неоновое свечение");
        ru.put("desc_FreeLook", "Свободный взгляд");
        ru.put("desc_FreeCam", "Свободная камера");
        ru.put("desc_ViewClip", "Сквозь блоки");
        ru.put("desc_Step", "Шаг вверх");
        ru.put("desc_ReverseStep", "Тянуть вниз");
        ru.put("desc_Commands", "Команды");
        ru.put("desc_ItemPhysics", "Физика предметов");
        ru.put("desc_Sounds", "Звуки");
        ru.put("desc_AntiHunger", "Без голода");
        ru.put("desc_AutoSign", "Заполнять таблички");
        ru.put("desc_AutoShear", "Стричь овец");
        ru.put("desc_AutoNameTag", "Называть животных");
        ru.put("desc_AutoMount", "Садиться на животных");
        ru.put("desc_RideExploit", "Ездить на чём угодно");
        ru.put("desc_AntiVoid", "Спасение от пустоты");
        ru.put("desc_AutoMend", "Ремонт снаряжения");
        ru.put("desc_FakePlayer", "Фейковый игрок");
        ru.put("desc_NoDelay", "Без задержек");
        ru.put("desc_AutoRespawn", "Мгновенное возрождение");
        ru.put("desc_AutoArmor", "Автоодевание брони");
        ru.put("desc_FastItem", "Быстрое перемещение");
        ru.put("desc_LongJump", "Длинный прыжок");
        ru.put("desc_AutoLog", "Уходить из боя");
        ru.put("desc_WebAura", "Ставить паутину");
        ru.put("desc_MaceAura", "Атака булавой");
        ru.put("desc_AutoTotem", "Автототем");
        ru.put("desc_Hitboxes", "Большие хитбоксы");
        ru.put("desc_Sleepy", "Скольжение");
        ru.put("desc_Reach", "Увеличенная дистанция");
        ru.put("desc_NoPush", "Без толчков");
        ru.put("desc_FastBreak", "Быстрое разрушение");
        ru.put("desc_InstaBreak", "Мгновенное разрушение");
        ru.put("desc_GhostHand", "Открывать сквозь стены");
        ru.put("desc_AutoSprint", "Автоспринт");
        ru.put("desc_Spider", "Лазать по стенам");
        ru.put("desc_Timer", "Ускорение");
        ru.put("desc_Speed", "Скорость");
        ru.put("desc_Xray", "Рентген");
        ru.put("desc_Surround", "Защита ног");
        ru.put("desc_BlockOutline", "Подсветка блоков");
        ru.put("desc_Fullbright", "Яркость");
        ru.put("desc_GuiParticles", "Частицы в меню");
        ru.put("desc_NoRotate", "Убрать поворот головы");
        ru.put("desc_NoRender", "Скрытие объектов");
        ru.put("desc_AutoWalk", "Автоходьба");
        ru.put("desc_MobOwner", "Владелец моба");
        ru.put("desc_SelfTrap", "Заблокировать себя");
        ru.put("desc_WaxAura", "Вощить медь");
        ru.put("desc_ChestAura", "Ставить сундуки");
        ru.put("desc_PortalGui", "Использовать в портале");
        ru.put("desc_Avoid", "Избегать урона");
        ru.put("desc_TabHelper", "Улучшенный таб");
        ru.put("desc_ChatHelper", "Помощники чата");
        ru.put("desc_ChestHelper", "Помощники сундуков");
        ru.put("desc_AutoReconnect", "Перезаходить на сервер");
        ru.put("desc_FastLatency", "Быстрый пинг");
        ru.put("desc_MultiTask", "Два дела сразу");
        ru.put("desc_BlockMixer", "Перемешивание блоков");
        ru.put("desc_AutoSoup", "Пить суп");
        ru.put("desc_NameProtect", "Скрыть имена");
        ru.put("desc_StashFinder", "Поиск лута");
        ru.put("desc_ClickTP", "Клик телепорт");
        ru.put("desc_ClickFly", "Клик полёт");
        ru.put("desc_ChorusExploit", "Сохранение телепорта");
        ru.put("desc_TickShift", "Накопление тиков");
        ru.put("desc_TridentBoost", "Ускорение трезубцем");
        ru.put("desc_WindAura", "Бросать ветер");
        ru.put("desc_BreadCrumbs", "Показать след");
        ru.put("desc_ViewModel", "Двигать руки");
        ru.put("desc_AutoCrystal", "Бить кристаллы");
        ru.put("desc_Trap", "Заблокировать врага");
        ru.put("desc_Igniter", "Поджигать TNT");
        ru.put("desc_RidingHelper", "Быстрая езда");
        ru.put("desc_Blink", "Задержка движений");
        ru.put("desc_PacketFly", "Пакетный полёт");
        ru.put("desc_BoatFly", "Полёт на лодке");
        ru.put("desc_AutoApple", "Автояблоко");
        ru.put("desc_TreeCutter", "Рубить деревья");
        ru.put("desc_FakePearl", "Фейковый жемчуг");
        ru.put("desc_BasePlace", "Ставить обсидиан");
        ru.put("desc_AnchorAura", "Взрывать якоря");
        ru.put("desc_ElytraHelper", "Смена элитры");
        ru.put("desc_ViewLock", "Заблокировать взгляд");
        ru.put("desc_ItemSaver", "Сохранить предметы");
        ru.put("desc_AntiAim", "Вращать голову");
        ru.put("desc_NoSwing", "Убрать взмах");
        ru.put("desc_SwingAnimation", "Анимация взмаха");
        ru.put("desc_CityESP", "Подсветка блоков для таргета");
        ru.put("desc_DesktopGui", "Управление с ПК");
        ru.put("desc_Breaker", "Ломать рядом");
        ru.put("desc_BowAim", "Наводка лука");
        ru.put("desc_Quiver", "Стрелять стрелами");
        ru.put("desc_DurabAlert", "Предупреждение о прочности");
        ru.put("desc_AntiAttack", "Без ударов по своим");
        ru.put("desc_LagNotify", "Предупреждение о лагах");
        ru.put("desc_PopCounter", "Счётчик тотемов");
        ru.put("desc_BookHelper", "Редактор книг");
        ru.put("desc_WebSelf", "Паутина на себя");
        ru.put("desc_KeyPearl", "Бросок жемчуга");
        ru.put("desc_AutoAuth", "Автовход");
        ru.put("desc_SafeWalk", "Безопасная ходьба");


        ru.put("desc_ShieldFucker", "Ломать щиты");
        ru.put("desc_KillEffects", "Эффекты смерти");
        ru.put("desc_AntiQuit", "Блокировать выход");
        ru.put("desc_CoordLogger", "Лог координат");
        ru.put("desc_Religion", "Религии");
        ru.put("desc_Phase", "Сквозь стены");
        ru.put("desc_MineAnimation", "Убрать трещины");
        ru.put("desc_HighJump", "Высокий прыжок");
        ru.put("desc_FastStairs", "Быстрые ступеньки");
        ru.put("desc_NoFall", "Без урона от падения");
        ru.put("desc_ElytraPlusPlus", "Элитра полёт");
        ru.put("desc_Flight", "Полёт в разных режимах");
        ru.put("desc_Disabler", "Вырубает просто все нахуй");
        ru.put("desc_Replenish", "Пополнять предметы");


        ru.put("desc_AutoReplant", "Сажать заново");
        ru.put("desc_Nuker", "Массовое разрушение");
        ru.put("desc_AutoTrade", "Торговля с жителями");
        ru.put("desc_AutoFish", "Авторыбалка");
        ru.put("desc_AutoTunnel", "Копать тоннель");


        ru.put("desc_ECFarmer", "Ферма сундуков");
        ru.put("desc_GhostBlocks", "Убрать фейк-блоки");
        ru.put("desc_AntiPearl", "Предупреждение о жемчуге");
        ru.put("desc_BedBomb", "Взрывать кровати");
        ru.put("desc_Criticals", "Критические удары");
        ru.put("desc_AutoBow", "Спуск лука");
        ru.put("desc_HoleFill", "Заполнять ямы");
        ru.put("desc_AutoClicker", "Автокликер");
        ru.put("desc_AntiBot", "Блокировка ботов");
        ru.put("desc_AutoDrop", "Автовыброс");
        ru.put("desc_Burrow", "Спрятаться в блок");
        ru.put("desc_PacketMine", "Клик-майн");
        ru.put("desc_PacketHelper", "Сетевые инструменты");
        ru.put("desc_Borders", "Границы мира");
        ru.put("desc_Zoom", "Зум камеры");
        ru.put("desc_Blur", "Размытие фона");
        ru.put("desc_ToolTips", "Информация о предмете");
        ru.put("desc_ESP_Void", "Подсветка пустоты");
        ru.put("desc_AutoReGear", "Пополнять предметы");
        ru.put("desc_AntiReGear", "Ломать контейнеры");
        ru.put("desc_Skeleton", "Показать тела");
        ru.put("desc_ChatHud", "Оверлей чата");
        ru.put("desc_CooldownsHud", "Кулдауны предметов");
        ru.put("desc_IndicatorsHud", "Информация о цели");
        ru.put("desc_InvPreviewHud", "Превью инвентаря");
        ru.put("desc_MediaHud", "Информация о музыке");
        ru.put("desc_Settings", "Настройки клиента");
        ru.put("desc_TpsHud", "Скорость сервера");
        ru.put("desc_Calculator", "Калькулятор");
        ru.put("desc_Fonts", "Шрифты");
        ru.put("desc_PingSpoof", "Фейковый пинг");
        ru.put("desc_ShiftInterp", "Принудительный шифт");
        ru.put("desc_SmallUser", "Маленькие игроки");
        ru.put("desc_TntAura", "Бомбить врагов");
        ru.put("desc_Particles", "Красивые частицы");
        ru.put("desc_Crosshair", "Свой прицел");
        ru.put("desc_PearlTarget", "Отслеживать жемчуг");
        ru.put("desc_MiddleClick", "Средняя кнопка");
        ru.put("desc_Telemetry", "Отправка данных");
        ru.put("desc_Baritone", "Поиск пути");
        ru.put("desc_PauseBaritone", "Пауза пути");
        ru.put("desc_NewChunks", "Новые чанки");
        ru.put("desc_AutoCart", "Отправлять вагонетки");
        ru.put("desc_MessageAura", "Сообщать игрокам рядом");
        ru.put("hud_desc_Watermark", "Ватермарка RaveX на экране");
        ru.put("hud_desc_ArrayList", "Список активных модулей");
        ru.put("hud_desc_Coords", "Текущие координаты X Y Z");
        ru.put("hud_desc_Fps", "Счётчик FPS");
        ru.put("hud_desc_Media", "Сейчас играет из системы");
        ru.put("hud_desc_Indicators", "Дуговые индикаторы здоровья, брони, TPS, скорости и отдачи");
        ru.put("hud_desc_InvPreview", "Превью инвентаря и хотбара");
        ru.put("hud_desc_Chat", "Изменение позиции чата");
        ru.put("hud_desc_TPS", "Монитор тиков сервера");
        ru.put("hud_desc_Cooldowns", "Кулдауны предметов с процентами");
        ru.put("hud_desc_Currency", "Курсы валют CIS, NATO и BTC");
        ru.put("hud_desc_ServerBrand", "Бренд сервера через JNI");
        ru.put("desc_TargetHud", "Информация о цели");
        ru.put("hud_desc_TargetHud", "Отображает параметры цели, её здоровье, броню и предмет в руке.");
        ru.put("hud_editor_scale_hint", "Колёсико мыши: масштаб выбранного HUD элемента");
        ru.put("cmd_help", "Помощь");
        ru.put("cmd_config", "Конфиг");
        ru.put("cmd_calc", "Кальк");
        ru.put("cmd_toggle", "Тогл");
        ru.put("cmd_bind", "Бинд");
        ru.put("cmd_panic", "Паника");
        ru.put("cmd_say", "Сказать");
        ru.put("cmd_time", "Время");
        ru.put("cmd_modules", "Модули");
        ru.put("cmd_coords", "Коорды");
        ru.put("cmd_waypoint", "Вейпоинты");
        ru.put("cmd_friend", "Друзья");
        ru.put("cmd_plugins", "Плагины");
        ru.put("cmd_clear", "Очистка");
        ru.put("cmd_uuid", "UUID");
        ru.put("cmd_nbt", "NBT");
        ru.put("gui_tips_title", "Управление");
        ru.put("gui_tip_toggle", "ЛКМ - включить/выключить модуль");
        ru.put("gui_tip_settings", "ПКМ - настройки модуля");
        ru.put("gui_tip_bind", "СКМ - назначить клавишу");
        ru.put("gui_tip_gear", "Шестерёнка - есть настройки (ShowGear)");
        ru.put("gui_search_placeholder", "Поиск...");
        ru.put("cfg_title", "Конфигурации");
        ru.put("cfg_subtitle", "Управление пресетами клиента");
        ru.put("cfg_saved", "Сохранённые пресеты");
        ru.put("cfg_empty", "Сохранённых пресетов пока нет.");
        ru.put("cfg_empty_hint", "Нажмите «Создать» ниже.");
        ru.put("cfg_no_selected", "Пресет не выбран");
        ru.put("cfg_not_in_world", "Не в мире");
        ru.put("cfg_save_new", "Создать");
        ru.put("cfg_save", "Сохранить");
        ru.put("cfg_load", "Загрузить");
        ru.put("cfg_delete", "Удалить");
        ru.put("cfg_back", "Назад");
        ru.put("cfg_cancel", "Отмена");
        ru.put("cfg_name_hint", "Имя пресета...");
        ru.put("prof_title", "Менеджер профилей");
        ru.put("prof_subtitle", "Сохраняй и загружай конфигурации модулей");
        ru.put("prof_apply", "Применить");
        ru.put("prof_capture", "Сохранить");
        ru.put("prof_refresh", "Обновить");
        ru.put("prof_refreshed", "Обновлено");
        ru.put("prof_save", "Сохранить");
        ru.put("prof_name_hint", "Имя профиля...");
        ru.put("macro_title", "Редактор макросов");
        ru.put("macro_new", "Новый макрос");
        ru.put("macro_none", "Нет");
        ru.put("macro_press_key", "Нажми клавишу...");
        ru.put("macro_enter_value", "Введи значение...");
        ru.put("macro_add_action", "Добавить действие");
        ru.put("macro_delete", "Удалить");
        ru.put("macro_done", "Готово");
        ru.put("macro_edit", "Изменить");
        ru.put("macro_create", "Создать");
        ru.put("macro_actions", "Действия");
        ru.put("macro_cmd", "Выполнить команду");
        ru.put("macro_chat", "Отправить в чат");
        ru.put("macro_toggle", "Переключить модуль");
        ru.put("hud_editor_title", "HUD-редактор RaveX");
        ru.put("pal_title", "Палитра цветов");
        ru.put("pal_presets", "Пресеты");
        ru.put("pal_recent", "Недавние");
        ru.put("pal_rainbow", "Радуга");
        ru.put("pal_positive", "Позитив");
        ru.put("arg_title", "Редактор наборов AutoReGear");
        ru.put("arg_subtitle", "Конфигурация наборов AutoReGear");
        ru.put("ic_title", "Чистильщик инвентаря");
        ru.put("ic_quit", "Выход");
        ru.put("ob_welcome_title", "Добро пожаловать в RaveX");
        ru.put("ob_welcome_sub", "Современный утилитарный клиент для Minecraft. Настроим пару вещей.");
        ru.put("ob_continue", "Продолжить");
        ru.put("ob_lang_title", "Выбери язык клиента");
        ru.put("ob_lang_sub", "Весь клиент будет отображаться на этом языке.");
        ru.put("ob_lang_en_name", "English");
        ru.put("ob_lang_en_sub", "International");
        ru.put("ob_lang_ru_name", "Русский");
        ru.put("ob_lang_ru_sub", "Россия");
        ru.put("ob_done_title", "Всё готово!");
        ru.put("ob_done_sub", "Нажми Enter или кнопку, чтобы войти.");
        ru.put("ob_enter", "Войти в RaveX");
        ru.put("ob_skip_hint", "ESC - пропустить");
        ru.put("cfg_selected", "Выбран:");
        ru.put("cfg_save_as", "Сохранить пресет как:");
        ru.put("cfg_auto", "АВТО");
        ru.put("cfg_model_slim", "Модель Alex");
        ru.put("cfg_model_wide", "Модель Steve");
        ru.put("prof_save_as", "Сохранить профиль как:");
        ru.put("prof_applied", "Профиль «{0}» применён");
        ru.put("prof_deleted", "Профиль «{0}» удалён");
        ru.put("prof_saved", "Профиль «{0}» сохранён");
        ru.put("macro_subtitle", "Макросы на клавиши с несколькими действиями");
        ru.put("macro_empty", "Макросов пока нет. Нажми «Создать».");
        ru.put("macro_name", "Имя:");
        ru.put("macro_editing", "Редактирование: ");
        ru.put("macro_add_action_label", "Добавить действие:");
        ru.put("macro_type", "Тип: ");
        ru.put("macro_bind", "Бинд: ");
        ru.put("macro_delay", "Задержка (мс)");
        ru.put("macro_deleted", "Макрос удалён");
        ru.put("macro_created", "Макрос «{0}» создан");
        ru.put("arg_back", "ESC / Назад");
        ru.put("arg_save_close", "Сохранить и закрыть");
        ru.put("ic_back", "ESC / Выход");
        ru.put("ic_page", "Страница {0} / {1}");
        ru.put("act_toggle", "Переключить: ");
        ru.put("act_chat", "Чат: ");
        ru.put("act_cmd", "Команда: ");
        ru.put("act_delay", "Задержка: ");
        ru.put("act_unknown", "Неизвестно");
        ru.put("gui_title", "КликГУИ RaveX");
        ru.put("gui_macros", "Макросы");
        ru.put("gui_profiles", "Профили");
        ru.put("gui_configs", "Конфиги");
        ru.put("gui_reset", "Сброс");
        ru.put("gui_hud", "HUD");
        ru.put("mb_binding", "Привязка");
        ru.put("mb_key", "Клавиша ");

        STRINGS.put("English", en);
        STRINGS.put("Russian", ru);
    }

    public static void setLanguage(String lang) {
        if (STRINGS.containsKey(lang)) currentLang = lang;
    }

    public static String getLanguage() {
        return currentLang;
    }

    public static String moduleName(String name) {
        return name;
    }

    public static String categoryName(String category) {
        return category;
    }

    public static String paramName(String name) {
        return name;
    }

    public static String cmdName(String cmdKey) {
        return t("cmd_" + cmdKey, cmdKey);
    }

    public static String t(String key, Object... args) {
        Map<String, String> lang = STRINGS.get(currentLang);
        if (lang == null) lang = STRINGS.get("English");
        String template = lang.get(key);
        if (template == null) template = STRINGS.get("English").getOrDefault(key, key);
        return format(template, args);
    }

    public static String getDescription(String moduleName) {
        String key = "desc_" + moduleName;
        String result = t(key);
        if (!result.equals(key)) return result;
        key = "hud_desc_" + moduleName;
        result = t(key);
        if (!result.equals(key)) return result;
        return null;
    }

    public static String getModeDescription(String paramName, String modeName) {
        String key = "desc_mode_" + paramName + "_" + modeName;
        String result = t(key);
        if (!result.equals(key)) return result;
        if ("Snap2".equalsIgnoreCase(modeName)) {
            return "Russian".equalsIgnoreCase(getLanguage())
                ? "Альтернатива Snap (наводись на цель)"
                : "Alternative to Snap (aim at target)";
        }
        return null;
    }

    private static String format(String template, Object... args) {
        if (args == null || args.length == 0) return template;
        String result = template;
        for (int i = 0; i < args.length; i++) {
            result = result.replace("{" + i + "}", args[i] != null ? args[i].toString() : "");
        }
        return result;
    }
}
