package ravex.utility.misc;
import java.util.HashMap;
import java.util.Map;
public class LanguageUtility {
    private static String currentLang = "English";
    private static final Map<String, Map<String, String>> STRINGS = new HashMap<>();

    static {
        Map<String, String> en = new HashMap<>();
        en.put("entered", "§f{0} §7entered");
        en.put("left", "§f{0} §7left");
        en.put("pickup", "§f{0} §7pickup §f{1}");
        en.put("ate_gapple", "§f{0} §7ate §eGolden Apple");
        en.put("ate_egapple", "§f{0} §7ate §dEnchanted Golden Apple");
        en.put("drank", "§f{0} §7drank {1}");
        en.put("pop_totem", "§f{0} §7pop §cTotem");
        en.put("shield_broke", "§f{0} §7shield broke");
        en.put("desc_KillAura", "Attack enemies");
        en.put("desc_ESP", "See through walls");
        en.put("desc_AutoTool", "Swap best tool");
        en.put("desc_AntiAfk", "No idle kick");
        en.put("desc_PVEUtils", "Smelt, tame, brew, bone meal & light");
        en.put("desc_ClickGui", "Open menu");
        en.put("desc_Notifications", "Screen alerts");
        en.put("desc_DeathText", "Death message");
        en.put("desc_SoundBlock", "Mute sounds");
        en.put("desc_InvClean", "Clean inventory");
        en.put("desc_Handshake", "Fake handshake");
        en.put("desc_PortalGod", "Portal shield");
        en.put("desc_LiquidControl", "Swim freely");
        en.put("desc_AutoWither", "Build wither");
        en.put("desc_AutoPortal", "Build portals");
        en.put("desc_NoBob", "No head bob");
        en.put("desc_Ambient", "Change light");
        en.put("desc_Weather", "Change weather");
        en.put("desc_WorldColor", "World colors");
        en.put("desc_Trails", "Show paths");
        en.put("desc_AspectRatio", "Stretch screen");
        en.put("desc_Waypoint", "Save locations");
        en.put("desc_AimAssist", "Aim helper");
        en.put("desc_NameTags", "Show names");
        en.put("desc_Tracers", "Draw lines");
        en.put("desc_Trigger", "Attack on hover");
        en.put("desc_MaceSwap", "Swap to mace");
        en.put("desc_Hud", "Screen overlay");
        en.put("desc_NoWeb", "Walk through webs");
        en.put("desc_Glint", "Item glow");
        en.put("desc_RichPresence", "Discord status");
        en.put("desc_GuiMove", "Walk in menus");
        en.put("desc_NoSlow", "No slow down");
        en.put("desc_Velocity", "Change knockback");
        en.put("desc_AutoEat", "Eat food");
        en.put("desc_NoInteract", "No misclicks");
        en.put("desc_SourceFiller", "Remove water");
        en.put("desc_AirPlace", "Place in air");
        en.put("desc_Scaffold", "Place bridges");
        en.put("desc_Shaders", "Neon glow");
        en.put("desc_FreeLook", "Free look");
        en.put("desc_FreeCam", "Free camera");
        en.put("desc_ViewClip", "See through blocks");
        en.put("desc_Step", "Step up");
        en.put("desc_ReverseStep", "Pull down");
        en.put("desc_Commands", "Run commands");
        en.put("desc_ItemPhysics", "Item physics");
        en.put("desc_Sounds", "Play sounds");
        en.put("desc_AntiHunger", "No hunger");
        en.put("desc_AutoSign", "Fill signs");
        en.put("desc_AutoShear", "Shear sheep");
        en.put("desc_AutoNameTag", "Name animals");
        en.put("desc_AutoMount", "Ride animals");
        en.put("desc_RideExploit", "Ride anything");
        en.put("desc_AntiVoid", "Void save");
        en.put("desc_AutoMend", "Repair gear");
        en.put("desc_FakePlayer", "Practice dummy");
        en.put("desc_NoDelay", "No delay");
        en.put("desc_AutoRespawn", "Instant respawn");
        en.put("desc_AutoArmor", "Equip armor");
        en.put("desc_FastItem", "Quick item move");
        en.put("desc_LongJump", "Jump far");
        en.put("desc_AutoLog", "Leave fight");
        en.put("desc_WebAura", "Place webs");
        en.put("desc_MaceAura", "Mace smash");
        en.put("desc_AutoTotem", "Swap totems");
        en.put("desc_Hitboxes", "Bigger targets");
        en.put("desc_Sleepy", "Slide around");
        en.put("desc_Reach", "Longer reach");
        en.put("desc_NoPush", "No push");
        en.put("desc_FastBreak", "Break fast");
        en.put("desc_InstaBreak", "Instant break");
        en.put("desc_GhostHand", "Open through walls");
        en.put("desc_AutoSprint", "Always sprint");
        en.put("desc_Spider", "Climb walls");
        en.put("desc_Timer", "Speed up");
        en.put("desc_Speed", "Move fast");
        en.put("desc_Xray", "See ores");
        en.put("desc_Surround", "Protect feet");
        en.put("desc_BlockOutline", "Block highlight");
        en.put("desc_Fullbright", "Always bright");
        en.put("desc_GuiParticles", "Menu sparkles");
        en.put("desc_NoRotate", "No head turn");
        en.put("desc_NoRender", "Hide things");
        en.put("desc_AutoWalk", "Walk forward");
        en.put("desc_MobOwner", "Show owner");
        en.put("desc_SelfTrap", "Trap yourself");
        en.put("desc_WaxAura", "Wax copper");
        en.put("desc_ChestAura", "Place chests");
        en.put("desc_PortalGui", "Use in portals");
        en.put("desc_Avoid", "Avoid damage");
        en.put("desc_TabHelper", "Better list");
        en.put("desc_ChatHelper", "Chat helpers");
        en.put("desc_ChestHelper", "Chest helpers");
        en.put("desc_AutoReconnect", "Rejoin server");
        en.put("desc_FastLatency", "Fast ping");
        en.put("desc_MultiTask", "Do two things");
        en.put("desc_BlockMixer", "Shuffle blocks");
        en.put("desc_AutoSoup", "Drink soup");
        en.put("desc_NameProtect", "Hide names");
        en.put("desc_StashFinder", "Find loot");
        en.put("desc_ClickTP", "Click teleport");
        en.put("desc_ClickFly", "Click to fly");
        en.put("desc_ChorusExploit", "Save teleport");
        en.put("desc_TickShift", "Store bursts");
        en.put("desc_TridentBoost", "Trident boost");
        en.put("desc_WindAura", "Throw wind");
        en.put("desc_BreadCrumbs", "Show trail");
        en.put("desc_ViewModel", "Move hands");
        en.put("desc_AutoCrystal", "Break crystals");
        en.put("desc_Trap", "Trap targets");
        en.put("desc_Igniter", "Light TNT");
        en.put("desc_RidingHelper", "Faster riding");
        en.put("desc_Blink", "Delay moves");
        en.put("desc_PacketFly", "Packet flight with GrimAC & NCP bypass");
        en.put("desc_AutoApple", "Eat apples");
        en.put("desc_TreeCutter", "Cut trees");
        en.put("desc_FakePearl", "Fake pearl");
        en.put("desc_BasePlace", "Place obsidian");
        en.put("desc_AnchorAura", "Explode anchors");
        en.put("desc_ElytraHelper", "Elytra swap");
        en.put("desc_ViewLock", "Lock view");
        en.put("desc_ItemSaver", "Save items");
        en.put("desc_AntiAim", "Spin head");
        en.put("desc_NoSwing", "No swing");
        en.put("desc_Animations", "Smooth moves");
        en.put("desc_SwingAnimation", "Swing animation");
        en.put("desc_DesktopGui", "Desktop control");
        en.put("desc_Breaker", "Break nearby");
        en.put("desc_BowAim", "Aim bow");
        en.put("desc_Quiver", "Shoot arrows");
        en.put("desc_DurabAlert", "Low durability");
        en.put("desc_AntiAttack", "No friendly hits");
        en.put("desc_LagNotify", "Lag warning");
        en.put("desc_PopCounter", "Count totems");
        en.put("desc_BookHelper", "Edit books");
        en.put("desc_WebSelf", "Web yourself");
        en.put("desc_KeyPearl", "Throw pearl");
        en.put("desc_AutoAuth", "Login helper");
        en.put("desc_SafeWalk", "Safe walk");


        en.put("desc_ShieldFucker", "Break shields");
        en.put("desc_KillEffects", "Death effects");
        en.put("desc_AntiQuit", "No leaving");
        en.put("desc_CoordLogger", "Log position");
        en.put("desc_Religion", "Show religions");
        en.put("desc_Phase", "Walk through walls");
        en.put("desc_MineAnimation", "Hide cracks");
        en.put("desc_HighJump", "High jump");
        en.put("desc_FastStairs", "Climb fast");
        en.put("desc_NoFall", "Safe fall");
        en.put("desc_ElytraPlusPlus", "Elytra fly");
        en.put("desc_Flight", "Creative fly");
        en.put("desc_Replenish", "Refill items");


        en.put("desc_AutoReplant", "Replant crops");
        en.put("desc_Nuker", "Mass break");
        en.put("desc_AutoTrade", "Trade villagers");
        en.put("desc_AutoFish", "Catch fish");
        en.put("desc_AutoTunnel", "Dig tunnel");


        en.put("desc_ECFarmer", "Farm chests");
        en.put("desc_GhostBlocks", "No fake blocks");
        en.put("desc_AntiPearl", "Pearl warning");
        en.put("desc_BedBomb", "Blow beds");
        en.put("desc_Criticals", "Crit hits");
        en.put("desc_AutoBow", "Release bow");
        en.put("desc_HoleFill", "Fill holes");
        en.put("desc_AutoClicker", "Click fast");
        en.put("desc_AntiBot", "Block bots");
        en.put("desc_AutoDrop", "Drop blocks");

        en.put("desc_Burrow", "Hide in block");
        en.put("desc_PacketMine", "Click mine");
        en.put("desc_PacketHelper", "Network tools");
        en.put("desc_Borders", "Show borders");
        en.put("desc_Zoom", "Camera zoom");
        en.put("desc_Blur", "Blur background");
        en.put("desc_ToolTips", "Item info");
        en.put("desc_ESP_Void", "Show void");
        en.put("desc_AutoReGear", "Refill items");
        en.put("desc_AntiReGear", "Break containers");
        en.put("desc_Skeleton", "Show bodies");
        en.put("desc_ChatHud", "Chat overlay");
        en.put("desc_CooldownsHud", "Show cooldowns");
        en.put("desc_IndicatorsHud", "Target info");
        en.put("desc_InvPreviewHud", "Preview items");
        en.put("desc_MediaHud", "Music info");
        en.put("desc_Settings", "Client settings");
        en.put("desc_TpsHud", "Server speed");
        en.put("desc_Calculator", "Do math");
        en.put("desc_Fonts", "Change fonts");
        en.put("desc_PingSpoof", "Fake ping");
        en.put("desc_ShiftInterp", "Force crouch");
        en.put("desc_SmallUser", "Small players");
        en.put("desc_TntAura", "Bomb targets");
        en.put("desc_GridBuilder", "Build grids");
        en.put("desc_Particles", "Pretty particles");
        en.put("desc_Crosshair", "Custom crosshair");
        en.put("desc_PearlTarget", "Track pearls");
        en.put("desc_MiddleClick", "Middle click");
        en.put("desc_Telemetry", "Send data");
        en.put("desc_Baritone", "Find path");
        en.put("desc_PauseBaritone", "Pause path");
        en.put("desc_NewChunks", "New chunks");
        en.put("desc_AutoCart", "Send carts");
        en.put("desc_MessageAura", "Message nearby players");
        en.put("hud_desc_Watermark", "Renders the premium RaveX Client watermark on screen.");
        en.put("hud_desc_ArrayList", "Renders the active (enabled) modules array list.");
        en.put("hud_desc_Coords", "Renders player's current X, Y, Z coordinates.");
        en.put("hud_desc_Fps", "Renders the current game frames per second (FPS) count.");
        en.put("hud_desc_Media", "Shows currently playing music from your system.");
        en.put("hud_desc_Indicators", "Arc gauges for Health, Armor, TPS, Speed, and Knockback.");
        en.put("hud_desc_InvPreview", "Preview of your full inventory and selected hotbar slot.");
        en.put("hud_desc_Chat", "Repositions and scales the in-game chat box.");
        en.put("hud_desc_TPS", "Current server tick rate (TPS) monitor.");
        en.put("hud_desc_Cooldowns", "Displays item cooldowns (Ender Pearl, Chorus, etc.) with remaining percentage.");
        en.put("hud_desc_Currency", "Renders custom live/simulated currency exchange rates for CIS & NATO countries + BTC.");
        en.put("hud_desc_ServerBrand", "Displays the server implementation brand using C++ JNI formatting.");
        en.put("desc_TargetHud", "Target info");
        en.put("hud_desc_TargetHud", "Displays target player statistics, health, armor, and hand items.");
        en.put("cmd_help", "Help");
        en.put("cmd_config", "Config");
        en.put("cmd_calc", "Calc");
        en.put("cmd_toggle", "Toggle");
        en.put("cmd_bind", "Bind");
        en.put("cmd_panic", "Panic");
        en.put("cmd_say", "Say");
        en.put("cmd_time", "Time");
        en.put("cmd_modules", "Modules");
        en.put("cmd_coords", "Coords");
        en.put("cmd_waypoint", "Waypoint");
        en.put("cmd_friend", "Friend");
        en.put("cmd_plugins", "Plugins");
        en.put("cmd_clear", "Clear");
        en.put("cmd_uuid", "UUID");
        en.put("cmd_nbt", "NBT");

        Map<String, String> ru = new HashMap<>();
        ru.put("entered", "§f{0} §7зашёл");
        ru.put("left", "§f{0} §7вышел");
        ru.put("pickup", "§f{0} §7подобрал §f{1}");
        ru.put("ate_gapple", "§f{0} §7съел §eЗолотое Яблоко");
        ru.put("ate_egapple", "§f{0} §7съел §dЗачарованное Золотое Яблоко");
        ru.put("drank", "§f{0} §7выпил {1}");
        ru.put("pop_totem", "§f{0} §7попнул §cТотем");
        ru.put("shield_broke", "§f{0} §7сломал щит");
        ru.put("desc_KillAura", "Атака врагов");
        ru.put("desc_ESP", "Видеть сквозь стены");
        ru.put("desc_AutoTool", "Автосмена инструмента");
        ru.put("desc_AntiAfk", "Не уходить в AFK");
        ru.put("desc_PVEUtils", "Плавка, приручение, варка, удобрение и свет");
        ru.put("desc_ClickGui", "Открыть меню");
        ru.put("desc_Notifications", "Уведомления на экране");
        ru.put("desc_DeathText", "Кастомный текст смерти");
        ru.put("desc_SoundBlock", "Блокировка звуков");
        ru.put("desc_InvClean", "Очистка инвентаря");
        ru.put("desc_Handshake", "Подмена рукопожатия");
        ru.put("desc_PortalGod", "Неуязвимость в портале");
        ru.put("desc_LiquidControl", "Контроль жидкости");
        ru.put("desc_AutoWither", "Автостройка визера");
        ru.put("desc_AutoPortal", "Автостройка порталов");
        ru.put("desc_NoBob", "Убрать качание головы");
        ru.put("desc_Ambient", "Изменить освещение");
        ru.put("desc_Weather", "Изменить погоду");
        ru.put("desc_WorldColor", "Цвета мира");
        ru.put("desc_Trails", "Показать путь");
        ru.put("desc_AspectRatio", "Растянуть экран");
        ru.put("desc_Waypoint", "Сохранение точек");
        ru.put("desc_AimAssist", "Помощь в прицеле");
        ru.put("desc_NameTags", "Показывать имена");
        ru.put("desc_Tracers", "Линии к игрокам");
        ru.put("desc_Trigger", "Атака при наведении");
        ru.put("desc_MaceSwap", "Свап на булаву");
        ru.put("desc_Hud", "Экранная накладка");
        ru.put("desc_NoWeb", "Ходьба в паутине");
        ru.put("desc_Glint", "Свечение предметов");
        ru.put("desc_RichPresence", "Статус в Discord");
        ru.put("desc_GuiMove", "Ходьба в меню");
        ru.put("desc_NoSlow", "Без замедления");
        ru.put("desc_Velocity", "Изменение отдачи");
        ru.put("desc_AutoEat", "Автоед");
        ru.put("desc_NoInteract", "Без лишних кликов");
        ru.put("desc_SourceFiller", "Убрать воду");
        ru.put("desc_AirPlace", "Ставить в воздухе");
        ru.put("desc_Scaffold", "Автомост");
        ru.put("desc_Shaders", "Неоновое свечение");
        ru.put("desc_FreeLook", "Свободный взгляд");
        ru.put("desc_FreeCam", "Свободная камера");
        ru.put("desc_ViewClip", "Сквозь блоки");
        ru.put("desc_Step", "Шаг вверх");
        ru.put("desc_ReverseStep", "Тянуть вниз");
        ru.put("desc_Commands", "Команды");
        ru.put("desc_ItemPhysics", "Физика предметов");
        ru.put("desc_Sounds", "Звуки");
        ru.put("desc_AntiHunger", "Без голода");
        ru.put("desc_AutoSign", "Заполнять таблички");
        ru.put("desc_AutoShear", "Стричь овец");
        ru.put("desc_AutoNameTag", "Называть животных");
        ru.put("desc_AutoMount", "Садиться на животных");
        ru.put("desc_RideExploit", "Ездить на чём угодно");
        ru.put("desc_AntiVoid", "Спасение от пустоты");
        ru.put("desc_AutoMend", "Ремонт снаряжения");
        ru.put("desc_FakePlayer", "Фейковый игрок");
        ru.put("desc_NoDelay", "Без задержек");
        ru.put("desc_AutoRespawn", "Мгновенное возрождение");
        ru.put("desc_AutoArmor", "Автоодевание брони");
        ru.put("desc_FastItem", "Быстрое перемещение");
        ru.put("desc_LongJump", "Длинный прыжок");
        ru.put("desc_AutoLog", "Уходить из боя");
        ru.put("desc_WebAura", "Ставить паутину");
        ru.put("desc_MaceAura", "Атака булавой");
        ru.put("desc_AutoTotem", "Автототем");
        ru.put("desc_Hitboxes", "Большие хитбоксы");
        ru.put("desc_Sleepy", "Скольжение");
        ru.put("desc_Reach", "Увеличенная дистанция");
        ru.put("desc_NoPush", "Без толчков");
        ru.put("desc_FastBreak", "Быстрое разрушение");
        ru.put("desc_InstaBreak", "Мгновенное разрушение");
        ru.put("desc_GhostHand", "Открывать сквозь стены");
        ru.put("desc_AutoSprint", "Автоспринт");
        ru.put("desc_Spider", "Лазать по стенам");
        ru.put("desc_Timer", "Ускорение");
        ru.put("desc_Speed", "Скорость");
        ru.put("desc_Xray", "Рентген");
        ru.put("desc_Surround", "Защита ног");
        ru.put("desc_BlockOutline", "Подсветка блоков");
        ru.put("desc_Fullbright", "Яркость");
        ru.put("desc_GuiParticles", "Частицы в меню");
        ru.put("desc_NoRotate", "Убрать поворот головы");
        ru.put("desc_NoRender", "Скрытие объектов");
        ru.put("desc_AutoWalk", "Автоходьба");
        ru.put("desc_MobOwner", "Владелец моба");
        ru.put("desc_SelfTrap", "Заблокировать себя");
        ru.put("desc_WaxAura", "Вощить медь");
        ru.put("desc_ChestAura", "Ставить сундуки");
        ru.put("desc_PortalGui", "Использовать в портале");
        ru.put("desc_Avoid", "Избегать урона");
        ru.put("desc_TabHelper", "Улучшенный таб");
        ru.put("desc_ChatHelper", "Помощники чата");
        ru.put("desc_ChestHelper", "Помощники сундуков");
        ru.put("desc_AutoReconnect", "Перезаходить на сервер");
        ru.put("desc_FastLatency", "Быстрый пинг");
        ru.put("desc_MultiTask", "Два дела сразу");
        ru.put("desc_BlockMixer", "Перемешивание блоков");
        ru.put("desc_AutoSoup", "Пить суп");
        ru.put("desc_NameProtect", "Скрыть имена");
        ru.put("desc_StashFinder", "Поиск лута");
        ru.put("desc_ClickTP", "Клик телепорт");
        ru.put("desc_ClickFly", "Клик полёт");
        ru.put("desc_ChorusExploit", "Сохранение телепорта");
        ru.put("desc_TickShift", "Накопление тиков");
        ru.put("desc_TridentBoost", "Ускорение трезубцем");
        ru.put("desc_WindAura", "Бросать ветер");
        ru.put("desc_BreadCrumbs", "Показать след");
        ru.put("desc_ViewModel", "Двигать руки");
        ru.put("desc_AutoCrystal", "Бить кристаллы");
        ru.put("desc_Trap", "Заблокировать врага");
        ru.put("desc_Igniter", "Поджигать TNT");
        ru.put("desc_RidingHelper", "Быстрая езда");
        ru.put("desc_Blink", "Задержка движений");
        ru.put("desc_PacketFly", "Пакетный полёт с обходом GrimAC и NCP");
        ru.put("desc_AutoApple", "Автояблоко");
        ru.put("desc_TreeCutter", "Рубить деревья");
        ru.put("desc_FakePearl", "Фейковый жемчуг");
        ru.put("desc_BasePlace", "Ставить обсидиан");
        ru.put("desc_AnchorAura", "Взрывать якоря");
        ru.put("desc_ElytraHelper", "Смена элитры");
        ru.put("desc_ViewLock", "Заблокировать взгляд");
        ru.put("desc_ItemSaver", "Сохранить предметы");
        ru.put("desc_AntiAim", "Вращать голову");
        ru.put("desc_NoSwing", "Убрать взмах");
        ru.put("desc_Animations", "Плавные движения");
        ru.put("desc_SwingAnimation", "Анимация взмаха");
        ru.put("desc_DesktopGui", "Управление с ПК");
        ru.put("desc_Breaker", "Ломать рядом");
        ru.put("desc_BowAim", "Наводка лука");
        ru.put("desc_Quiver", "Стрелять стрелами");
        ru.put("desc_DurabAlert", "Предупреждение о прочности");
        ru.put("desc_AntiAttack", "Без ударов по своим");
        ru.put("desc_LagNotify", "Предупреждение о лагах");
        ru.put("desc_PopCounter", "Счётчик тотемов");
        ru.put("desc_BookHelper", "Редактор книг");
        ru.put("desc_WebSelf", "Паутина на себя");
        ru.put("desc_KeyPearl", "Бросок жемчуга");
        ru.put("desc_AutoAuth", "Автовход");
        ru.put("desc_SafeWalk", "Безопасная ходьба");


        ru.put("desc_ShieldFucker", "Ломать щиты");
        ru.put("desc_KillEffects", "Эффекты смерти");
        ru.put("desc_AntiQuit", "Блокировать выход");
        ru.put("desc_CoordLogger", "Лог координат");
        ru.put("desc_Religion", "Религии");
        ru.put("desc_Phase", "Сквозь стены");
        ru.put("desc_MineAnimation", "Убрать трещины");
        ru.put("desc_HighJump", "Высокий прыжок");
        ru.put("desc_FastStairs", "Быстрые ступеньки");
        ru.put("desc_NoFall", "Без урона от падения");
        ru.put("desc_ElytraPlusPlus", "Элитра полёт");
        ru.put("desc_Flight", "Креативный полёт");
        ru.put("desc_Replenish", "Пополнять предметы");


        ru.put("desc_AutoReplant", "Сажать заново");
        ru.put("desc_Nuker", "Массовое разрушение");
        ru.put("desc_AutoTrade", "Торговля с жителями");
        ru.put("desc_AutoFish", "Авторыбалка");
        ru.put("desc_AutoTunnel", "Копать тоннель");


        ru.put("desc_ECFarmer", "Ферма сундуков");
        ru.put("desc_GhostBlocks", "Убрать фейк-блоки");
        ru.put("desc_AntiPearl", "Предупреждение о жемчуге");
        ru.put("desc_BedBomb", "Взрывать кровати");
        ru.put("desc_Criticals", "Критические удары");
        ru.put("desc_AutoBow", "Спуск лука");
        ru.put("desc_HoleFill", "Заполнять ямы");
        ru.put("desc_AutoClicker", "Автокликер");
        ru.put("desc_AntiBot", "Блокировка ботов");
        ru.put("desc_AutoDrop", "Автовыброс");
        ru.put("desc_Burrow", "Спрятаться в блок");
        ru.put("desc_PacketMine", "Клик-майн");
        ru.put("desc_PacketHelper", "Сетевые инструменты");
        ru.put("desc_Borders", "Границы мира");
        ru.put("desc_Zoom", "Зум камеры");
        ru.put("desc_Blur", "Размытие фона");
        ru.put("desc_ToolTips", "Информация о предмете");
        ru.put("desc_ESP_Void", "Подсветка пустоты");
        ru.put("desc_AutoReGear", "Пополнять предметы");
        ru.put("desc_AntiReGear", "Ломать контейнеры");
        ru.put("desc_Skeleton", "Показать тела");
        ru.put("desc_ChatHud", "Оверлей чата");
        ru.put("desc_CooldownsHud", "Кулдауны предметов");
        ru.put("desc_IndicatorsHud", "Информация о цели");
        ru.put("desc_InvPreviewHud", "Превью инвентаря");
        ru.put("desc_MediaHud", "Информация о музыке");
        ru.put("desc_Settings", "Настройки клиента");
        ru.put("desc_TpsHud", "Скорость сервера");
        ru.put("desc_Calculator", "Калькулятор");
        ru.put("desc_Fonts", "Шрифты");
        ru.put("desc_PingSpoof", "Фейковый пинг");
        ru.put("desc_ShiftInterp", "Принудительный шифт");
        ru.put("desc_SmallUser", "Маленькие игроки");
        ru.put("desc_TntAura", "Бомбить врагов");
        ru.put("desc_GridBuilder", "Строить сетки");
        ru.put("desc_Particles", "Красивые частицы");
        ru.put("desc_Crosshair", "Свой прицел");
        ru.put("desc_PearlTarget", "Отслеживать жемчуг");
        ru.put("desc_MiddleClick", "Средняя кнопка");
        ru.put("desc_Telemetry", "Отправка данных");
        ru.put("desc_Baritone", "Поиск пути");
        ru.put("desc_PauseBaritone", "Пауза пути");
        ru.put("desc_NewChunks", "Новые чанки");
        ru.put("desc_AutoCart", "Отправлять вагонетки");
        ru.put("desc_MessageAura", "Сообщать игрокам рядом");
        ru.put("hud_desc_Watermark", "Ватермарка RaveX на экране");
        ru.put("hud_desc_ArrayList", "Список активных модулей");
        ru.put("hud_desc_Coords", "Текущие координаты X Y Z");
        ru.put("hud_desc_Fps", "Счётчик FPS");
        ru.put("hud_desc_Media", "Сейчас играет из системы");
        ru.put("hud_desc_Indicators", "Дуговые индикаторы здоровья, брони, TPS, скорости и отдачи");
        ru.put("hud_desc_InvPreview", "Превью инвентаря и хотбара");
        ru.put("hud_desc_Chat", "Изменение позиции чата");
        ru.put("hud_desc_TPS", "Монитор тиков сервера");
        ru.put("hud_desc_Cooldowns", "Кулдауны предметов с процентами");
        ru.put("hud_desc_Currency", "Курсы валют CIS, NATO и BTC");
        ru.put("hud_desc_ServerBrand", "Бренд сервера через JNI");
        ru.put("desc_TargetHud", "Информация о цели");
        ru.put("hud_desc_TargetHud", "Отображает параметры цели, её здоровье, броню и предмет в руке.");
        ru.put("cmd_help", "Помощь");
        ru.put("cmd_config", "Конфиг");
        ru.put("cmd_calc", "Кальк");
        ru.put("cmd_toggle", "Тогл");
        ru.put("cmd_bind", "Бинд");
        ru.put("cmd_panic", "Паника");
        ru.put("cmd_say", "Сказать");
        ru.put("cmd_time", "Время");
        ru.put("cmd_modules", "Модули");
        ru.put("cmd_coords", "Коорды");
        ru.put("cmd_waypoint", "Вейпоинты");
        ru.put("cmd_friend", "Друзья");
        ru.put("cmd_plugins", "Плагины");
        ru.put("cmd_clear", "Очистка");
        ru.put("cmd_uuid", "UUID");
        ru.put("cmd_nbt", "NBT");

        STRINGS.put("English", en);
        STRINGS.put("Russian", ru);
    }

    public static void setLanguage(String lang) {
        if (STRINGS.containsKey(lang)) currentLang = lang;
    }

    public static String getLanguage() {
        return currentLang;
    }

    public static String cmdName(String cmdKey) {
        return t("cmd_" + cmdKey, cmdKey);
    }

    public static String t(String key, Object... args) {
        Map<String, String> lang = STRINGS.get(currentLang);
        if (lang == null) lang = STRINGS.get("English");
        String template = lang.get(key);
        if (template == null) template = STRINGS.get("English").getOrDefault(key, key);
        return format(template, args);
    }

    public static String getDescription(String moduleName) {
        String key = "desc_" + moduleName;
        String result = t(key);
        if (!result.equals(key)) return result;
        key = "hud_desc_" + moduleName;
        result = t(key);
        if (!result.equals(key)) return result;
        return null;
    }

    private static String format(String template, Object... args) {
        if (args == null || args.length == 0) return template;
        String result = template;
        for (int i = 0; i < args.length; i++) {
            result = result.replace("{" + i + "}", args[i] != null ? args[i].toString() : "");
        }
        return result;
    }
}
