/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ravex_modules_player_Replenish */

#ifndef _Included_ravex_modules_player_Replenish
#define _Included_ravex_modules_player_Replenish
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ravex_modules_player_Replenish
 * Method:    nativeFindReplenish
 * Signature: ([I[Ljava/lang/String;[I[I[Ljava/lang/String;[II)[I
 */
JNIEXPORT jintArray JNICALL Java_ravex_modules_player_Replenish_nativeFindReplenish
  (JNIEnv *, jclass, jintArray, jobjectArray, jintArray, jintArray, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
