package ravex.descriptions;

import java.util.HashMap;
import java.util.Map;

public class ClickGuiDescriptions {
    private static final Map<String, String> DESCRIPTIONS = new HashMap<>();

    static {
        DESCRIPTIONS.put("KillAura", "Auto attacks nearby hostile targets.");
        DESCRIPTIONS.put("ESP", "Renders glowing player outlines through walls.");
        DESCRIPTIONS.put("AutoTool", "Swaps to the most efficient tool automatically.");
        DESCRIPTIONS.put("AntiAfk", "Prevents AFK timeout kicks by moving.");
        DESCRIPTIONS.put("BoneMeal", "Automatically fertilizes crops with bonemeal.");
        DESCRIPTIONS.put("ClickGui", "Opens the GUI from any screen.");
        DESCRIPTIONS.put("Notifications", "Displays screen alerts for toggled modules.");
        DESCRIPTIONS.put("VisualRange", "Alerts you when players enter render range.");
        DESCRIPTIONS.put("NoBob", "Disables hand and camera bobbing physics.");
        DESCRIPTIONS.put("Ambient", "Changes world sky light and time tint color.");
        DESCRIPTIONS.put("Weather", "Visually changes world weather.");
        DESCRIPTIONS.put("CustomFog", "Modifies ambient fog density and color.");
        DESCRIPTIONS.put("SkyColor", "Recolor entire sky at will.");
        DESCRIPTIONS.put("CloudColor", "Override cloud color completely.");
        DESCRIPTIONS.put("Trails", "Trace projectile flight paths live.");
        DESCRIPTIONS.put("AspectRatio", "Change screen aspect ratio.");
        DESCRIPTIONS.put("Waypoint", "Set and navigate to waypoints.");
        DESCRIPTIONS.put("AimAssist", "Smoothly guides your crosshair toward targets.");
        DESCRIPTIONS.put("NameTags", "Displays high-fidelity HUD info above entities.");
        DESCRIPTIONS.put("Tracers", "Draws lines from the crosshair to entities.");
        DESCRIPTIONS.put("Trigger", "Attacks targets automatically when hovered.");
        DESCRIPTIONS.put("MaceSwap", "Swaps to Mace during falls.");
        DESCRIPTIONS.put("Hud", "Configures screen overlays and HUD positions.");
        DESCRIPTIONS.put("Optimizer", "Performs JVM and native RAM cleanups.");
        DESCRIPTIONS.put("NoWeb", "Bypasses slow cobweb movement physics.");
        DESCRIPTIONS.put("Glint", "Customizes item enchantment glow color.");
        DESCRIPTIONS.put("RichPresence", "Displays RaveX status on Discord profile.");
        DESCRIPTIONS.put("GuiWalk", "Allows moving around while inside menus.");
        DESCRIPTIONS.put("NoSlowDown", "Prevents slowdown from items.");
        DESCRIPTIONS.put("Velocity", "Reduces or cancels incoming knockback.");
        DESCRIPTIONS.put("AutoEat", "Eats food automatically when hunger is low.");
        DESCRIPTIONS.put("NoInteract", "Prevents accidental block and container clicks.");
        DESCRIPTIONS.put("SourceFiller", "Places sponges automatically to dry water.");
        DESCRIPTIONS.put("AirPlace", "Places blocks in mid-air with visual guides.");
        DESCRIPTIONS.put("Scaffold", "Places block bridges under player feet.");
        DESCRIPTIONS.put("Shaders", "Applies static neon glowing effects to players.");
        DESCRIPTIONS.put("FreeLook", "Enables 360 camera viewing without rotating.");
        DESCRIPTIONS.put("FreeCam", "Detaches camera for spectator-mode flying.");
        DESCRIPTIONS.put("ViewClip", "Allows third-person camera to pass through blocks.");
        DESCRIPTIONS.put("Step", "Instantly ascends up full blocks like stairs.");
        DESCRIPTIONS.put("ReverseStep", "Pulls you down to the ground instantly.");
        DESCRIPTIONS.put("Spammer", "Spams text or file contents into chat.");
        DESCRIPTIONS.put("Commands", "Enables control console for cheat commands.");
        DESCRIPTIONS.put("ItemPhysics", "Gives realistic physical physics to dropped items.");
        DESCRIPTIONS.put("Sounds", "Plays auditory effects on module actions.");
        DESCRIPTIONS.put("AntiHunger", "Blocks hunger depletion completely.");
        DESCRIPTIONS.put("AutoSign", "Fills signs with pre-configured text.");
        DESCRIPTIONS.put("AutoShear", "Shears sheep in proximity automatically.");
        DESCRIPTIONS.put("AutoNameTag", "Applies nametags to entities automatically.");
        DESCRIPTIONS.put("AutoMount", "Mounts horses, pigs, or boats automatically.");
        DESCRIPTIONS.put("RideExploit", "Rides any entity without saddles or reins.");
        DESCRIPTIONS.put("AntiVoid", "Protects from void falls.");
        DESCRIPTIONS.put("AutoMend", "Repairs armor automatically using XP bottles.");
        DESCRIPTIONS.put("FakePlayer", "Spawns a client-side practice combat dummy.");
        DESCRIPTIONS.put("FastUse", "Removes right-click placement delay limits.");
        DESCRIPTIONS.put("AutoRespawn", "Respawns player instantly upon death.");
        DESCRIPTIONS.put("AutoArmor", "Automatically equips the best armor.");
        DESCRIPTIONS.put("PacketLogger", "Logs network packets.");
        DESCRIPTIONS.put("PacketCanceller", "Blocks specific packets.");
        DESCRIPTIONS.put("HandshakeSpoof", "Spoofs client handshakes.");
        DESCRIPTIONS.put("LongJump", "Performs long horizontal jumps with boosts.");
        DESCRIPTIONS.put("AutoLog", "Disconnects during combat.");
        DESCRIPTIONS.put("WebAura", "Places cobwebs under target feet automatically.");
        DESCRIPTIONS.put("AutoWeapon", "Swaps to the best damage weapon on attack.");
        DESCRIPTIONS.put("MaceAura", "Deals massive fall damage with Mace instantly.");
        DESCRIPTIONS.put("Offhand", "Puts Totems, Gapples, or Shields in second hand.");
        DESCRIPTIONS.put("MainHand", "Puts selected combat items in primary hand.");
        DESCRIPTIONS.put("Hitboxes", "Expands target collision bounding box sizes.");
        DESCRIPTIONS.put("Sleepy", "Slide on any surface.");
        DESCRIPTIONS.put("Reach", "Increases player block and entity interaction ranges.");
        DESCRIPTIONS.put("NoPush", "Disables player physical pushing and rod pulling.");
        DESCRIPTIONS.put("FastBreak", "Sets minimum break delay between block attacks.");
        DESCRIPTIONS.put("InstaBreak", "Removes break delay entirely for instant breaking.");
        DESCRIPTIONS.put("GhostHand", "Interacts with containers through walls.");
        DESCRIPTIONS.put("AutoSprint", "Automatically sprints when moving forward.");
        DESCRIPTIONS.put("Spider", "Climbs up walls.");
        DESCRIPTIONS.put("Timer", "Accelerates game tick rate for faster movement.");
        DESCRIPTIONS.put("Speed", "Increases movement speed with various bypass modes.");
        DESCRIPTIONS.put("Xray", "Makes blocks transparent and outlines chosen blocks.");
        DESCRIPTIONS.put("Surround", "Places blocks around your feet for protection.");
        DESCRIPTIONS.put("BlockOutline", "Customizable highlight on the targeted block.");
        DESCRIPTIONS.put("Fullbright", "Makes everything bright.");
        DESCRIPTIONS.put("GuiParticles", "Renders animated particles in ClickGUI.");
        DESCRIPTIONS.put("NoRotate", "Prevents the server from rotating your head.");
        DESCRIPTIONS.put("NoRender", "Disables rendering of specific visuals.");
        DESCRIPTIONS.put("AutoWalk", "Automatically walks forward.");
        DESCRIPTIONS.put("MobOwner", "Displays the owner of tamed mobs.");
        DESCRIPTIONS.put("SelfTrap", "Automatically places blocks around yourself.");
        DESCRIPTIONS.put("WaxAura", "Automatically waxes nearby copper blocks.");
        DESCRIPTIONS.put("ChestAura", "Automatically places chests around the player or entities.");
        DESCRIPTIONS.put("PortalGui", "Use inventory and chat inside portals.");
        DESCRIPTIONS.put("Avoid", "Avoids damaging blocks like cacti and berries.");
        DESCRIPTIONS.put("ItemScroller", "Mass-drops and transfers items quickly.");
        DESCRIPTIONS.put("ExtraTab", "Extra tab utilities.");
        DESCRIPTIONS.put("ExtraChat", "Extra chat utilities.");
        DESCRIPTIONS.put("ExtraChest", "Extra chest utilities.");
        DESCRIPTIONS.put("AutoReconnect", "Adds reconnect button.");
        DESCRIPTIONS.put("FastLatency", "Measures ping more frequently for accurate RTT.");
        DESCRIPTIONS.put("MultiTask", "Allows attacking & mining while eating/using items.");
        DESCRIPTIONS.put("BlockSelector", "Selects blocks from hotbar after placing.");
        DESCRIPTIONS.put("AutoSoup", "Auto-drinks healing potions when health is low.");
        DESCRIPTIONS.put("NameProtect", "Hides player name in nametags and chat (→RaveX).");
        DESCRIPTIONS.put("StashFinder", "Detects & highlights stashes with valuable items.");
        DESCRIPTIONS.put("ClickTP", "Right-click anywhere to instantly teleport there.");
        DESCRIPTIONS.put("ClickFly", "Flies to clicked destinations.");
        DESCRIPTIONS.put("ChorusExploit", "Stores chorus teleport for later.");
        DESCRIPTIONS.put("TickShift", "Stores ticks for speed bursts.");
        DESCRIPTIONS.put("TridentBoost", "Boost your velocity when using a Riptide trident.");
        DESCRIPTIONS.put("WindAura", "Auto-throws wind charges at nearby entities.");
        DESCRIPTIONS.put("BreadCrumbs", "Draws trail lines behind you and other entities.");
        DESCRIPTIONS.put("ViewModel", "Customize hand position, rotation and scale.");
        DESCRIPTIONS.put("AutoCrystal", "Places and breaks End Crystals.");
        DESCRIPTIONS.put("Trap", "Boxes targets with solid blocks.");
        DESCRIPTIONS.put("Igniter", "Automatically ignites nearby TNT blocks.");
        DESCRIPTIONS.put("ExtraRocket", "Multiplies elytra velocity when using firework rockets.");
        DESCRIPTIONS.put("ExtraRiding", "Increases the speed of rideable entities.");
        DESCRIPTIONS.put("Blink", "Batches movement packets.");
        DESCRIPTIONS.put("PacketFly", "Manipulates packets to fly through the air.");
        DESCRIPTIONS.put("AutoApple", "Automatically eats golden apples under dangerous circumstances.");
        DESCRIPTIONS.put("TreeCutter", "Breaks tree logs automatically.");
        DESCRIPTIONS.put("FakePearl", "Throws a fake ender pearl.");
        DESCRIPTIONS.put("BasePlace", "Places obsidian for crystal damage.");
        DESCRIPTIONS.put("AnchorAura", "Places, charges, and explodes Respawn Anchors.");
        DESCRIPTIONS.put("ElytraSwap", "Swaps chestplate and elytra with customizable legitimacy modes.");
        DESCRIPTIONS.put("ElytraReplace", "Replaces elytra at low durability.");
        DESCRIPTIONS.put("ViewLock", "Locks camera rotation.");
        DESCRIPTIONS.put("ToolSaver", "Prevents tools from breaking.");
        DESCRIPTIONS.put("AntiAim", "Jitters or spins head rotation.");
        DESCRIPTIONS.put("NoSwing", "Prevent hand swing animation.");
        DESCRIPTIONS.put("Swing", "Change swing animation style.");
        DESCRIPTIONS.put("DesktopGui", "Native desktop control.");
        DESCRIPTIONS.put("Breaker", "Mines blocks around targets automatically.");
        DESCRIPTIONS.put("BowAim", "Aims bows at targets with prediction.");
        DESCRIPTIONS.put("Quiver", "Shoots beneficial arrows at yourself.");
        DESCRIPTIONS.put("DurabAlert", "Warns about low armor durability.");
        DESCRIPTIONS.put("AntiAttack", "Prevents hitting friendly entities.");
        DESCRIPTIONS.put("LagNotify", "Notifies when TPS drops.");
        DESCRIPTIONS.put("PopCounter", "Counts how many totems each player has popped.");
        DESCRIPTIONS.put("AntiBookBan", "Prevents crashes from malicious book data.");
        DESCRIPTIONS.put("AutoEZ", "Trash talks after kills.");
        DESCRIPTIONS.put("WebSelf", "Places web under your feet.");
        DESCRIPTIONS.put("KeyPearl", "Keybind to throw a pearl.");
        DESCRIPTIONS.put("KeepSprint", "Keep sprint after being hit.");
        DESCRIPTIONS.put("AutoAuth", "Auto /register and /login.");
        DESCRIPTIONS.put("SafeWalk", "Prevents falling off edges.");
        DESCRIPTIONS.put("AutoTame", "Auto tame wolves, cats, llamas.");
        DESCRIPTIONS.put("ShieldFucker", "Fucks shielded opponents.");
        DESCRIPTIONS.put("KillEffects", "Visual effects on entity death.");
        DESCRIPTIONS.put("AntiQuit", "Blocks game or server exit.");
        DESCRIPTIONS.put("CustomDeathText", "Custom death message.");
        DESCRIPTIONS.put("NoNarrator", "Force disable narrator.");
        DESCRIPTIONS.put("NoPacketKick", "Prevents kick from packet spam.");
        DESCRIPTIONS.put("SoundBlocker", "Block specific sound categories.");
        DESCRIPTIONS.put("Announcer", "Auto announce stats in chat.");
        DESCRIPTIONS.put("Welcomer", "Welcome new players to server.");
        DESCRIPTIONS.put("CoordLogger", "Log coordinates on events.");
        DESCRIPTIONS.put("Phase", "Pass through walls.");
        DESCRIPTIONS.put("RocketExtender", "Extends elytra firework rocket boost duration.");
        DESCRIPTIONS.put("RaytraceBypass", "Bypasses server-side block raytrace collision checks.");
        DESCRIPTIONS.put("NoMineAnimation", "Hides mining animations.");
        DESCRIPTIONS.put("HighJump", "Jump extremely high.");
        DESCRIPTIONS.put("FastStairs", "Speeds up stairs climbing using C++ JNI.");
        DESCRIPTIONS.put("NoFall", "Prevents fall damage using NCP/Grim bypass JNI.");
        DESCRIPTIONS.put("Elytra++", "Advanced elytra flight control.");
        DESCRIPTIONS.put("Flight", "Creative flight with various bypass modes.");
        DESCRIPTIONS.put("InventoryCleaner", "Select and auto-drop unwanted items from inventory.");
        DESCRIPTIONS.put("Replenish", "Auto-refills hotbar items from inventory when below threshold.");
        DESCRIPTIONS.put("AutoLight", "Automatically places torches in dark areas.");
        DESCRIPTIONS.put("AutoReplant", "Automatically replants crops on farmland.");
        DESCRIPTIONS.put("Nuker", "Breaks selected blocks in range.");
        DESCRIPTIONS.put("AutoTrade", "Automatically trades with villagers.");
        DESCRIPTIONS.put("AutoFish", "Automatically fishes and reels in catches.");
        DESCRIPTIONS.put("AutoTunnel", "Digs tunnels and fills lava.");
        DESCRIPTIONS.put("AutoSmelt", "Refuels and collects furnace results.");
        DESCRIPTIONS.put("AutoBrew", "Brews potions automatically.");
        DESCRIPTIONS.put("ECFarmer", "Farms ender chests automatically.");
        DESCRIPTIONS.put("NoGhostBlocks", "Removes ghost blocks.");
        DESCRIPTIONS.put("NoHitDelay", "Removes attack cooldown.");
        DESCRIPTIONS.put("AntiPearl", "Warns about incoming ender pearls.");
        DESCRIPTIONS.put("BedBomb", "Places and detonates beds.");
        DESCRIPTIONS.put("PortalBuild", "Builds and lights nether portals.");
        DESCRIPTIONS.put("Criticals", "Enables critical hits in various modes.");
        DESCRIPTIONS.put("AutoBow", "Auto-releases bow at configured charge with silent swap.");
        DESCRIPTIONS.put("HoleFill", "Fills holes with blocks.");
        DESCRIPTIONS.put("AutoClicker", "Clicks automatically with configurable CPS and jitter.");
        DESCRIPTIONS.put("AntiBot", "Detects and filters bots.");
        DESCRIPTIONS.put("AutoDrop", "Drops falling blocks on targets from above.");
        DESCRIPTIONS.put("SelfFill", "Fills blocks around you for protection.");
        DESCRIPTIONS.put("Burrow", "Pushes you inside a block for safety.");
        DESCRIPTIONS.put("PacketMine", "Click to auto-mine blocks with progress.");
        DESCRIPTIONS.put("PacketEat", "Packet-based instant eating with Auto/Manual modes.");
        DESCRIPTIONS.put("WitherBuild", "Builds wither structures.");

        DESCRIPTIONS.put("Borders", "Shows chunk borders and current chunk.");
        DESCRIPTIONS.put("Tunnels", "Highlights tunnel entrances nearby.");
        DESCRIPTIONS.put("Zoom", "Smooth camera zoom in and out.");
        DESCRIPTIONS.put("HoleESP", "Highlights holes with safety colors.");
        DESCRIPTIONS.put("Blur", "Blurs background in inventories.");
        DESCRIPTIONS.put("ToolTips", "Shows shulker contents and item info.");
        DESCRIPTIONS.put("VoidESP", "Highlights void areas below.");
        DESCRIPTIONS.put("AutoReGear", "Automatically refills items from containers.");
        DESCRIPTIONS.put("AntiReGear", "Automatically breaks nearby enemy containers.");
        DESCRIPTIONS.put("Skeleton", "Renders player skeleton models.");
        DESCRIPTIONS.put("ExtraBook", "Extra book editing utilities.");
        DESCRIPTIONS.put("BookFill", "Automatically fills writable books.");
        DESCRIPTIONS.put("ChatHud", "Custom chat overlay and filtering.");
        DESCRIPTIONS.put("CooldownsHud", "Displays item cooldowns on the HUD.");
        DESCRIPTIONS.put("IndicatorsHud", "Shows target info indicators on screen.");
        DESCRIPTIONS.put("InvPreviewHud", "Preview inventories on hover.");
        DESCRIPTIONS.put("NowPlayingHud", "Displays now playing track info.");
        DESCRIPTIONS.put("Settings", "Client settings and configuration.");
        DESCRIPTIONS.put("TpsHud", "Visualizes server TPS on the HUD.");
        DESCRIPTIONS.put("Calculator", "In-game calculator utility.");
        DESCRIPTIONS.put("Fonts", "Customize fonts, size and text appearance.");
        DESCRIPTIONS.put("PacketPlace", "Packet block placement.");
        DESCRIPTIONS.put("PingSpoof", "Spoof ping latency.");
        DESCRIPTIONS.put("ShiftInterp", "Forces fucking crouching.");
        DESCRIPTIONS.put("BabyDude", "Render fucking toddlers.");
        DESCRIPTIONS.put("LiquidCollision", "Bypass fucking liquids.");
        DESCRIPTIONS.put("TntAura", "Bombs fucking targets.");
        DESCRIPTIONS.put("WitherRoseAura", "Places roses.");
        DESCRIPTIONS.put("GridBuilder", "Builds 5x5 grid patterns on right-click.");
    }

    public static String getDescription(String moduleName) {
        return DESCRIPTIONS.getOrDefault(moduleName, "No description.");
    }
}
