package ravex.descriptions;

import java.util.HashMap;
import java.util.Map;

public class ClickGuiDescriptions {
    private static final Map<String, String> DESCRIPTIONS = new HashMap<>();

    static {
        DESCRIPTIONS.put("KillAura",      "Auto attacks nearby hostile targets.");
        DESCRIPTIONS.put("ESP",           "Renders glowing player outlines through walls.");
        DESCRIPTIONS.put("AutoTool",      "Swaps to the most efficient tool automatically.");
        DESCRIPTIONS.put("AntiAfk",       "Prevents AFK timeout kicks by moving.");
        DESCRIPTIONS.put("BoneMeal",      "Automatically fertilizes crops with bonemeal.");
        DESCRIPTIONS.put("ClickGui",      "GUI can be opened from any screen (menu, server list, in-game).");
        DESCRIPTIONS.put("Notifications", "Displays screen alerts for toggled modules.");
        DESCRIPTIONS.put("VisualRange",   "Alerts you when players enter render range.");
        DESCRIPTIONS.put("NoBob",         "Disables hand and camera bobbing physics.");
        DESCRIPTIONS.put("Ambient",       "Changes world sky light and time tint color.");
        DESCRIPTIONS.put("CustomFog",     "Modifies ambient fog density and color.");
        DESCRIPTIONS.put("AimAssist",     "Smoothly guides your crosshair toward targets.");
        DESCRIPTIONS.put("NameTags",      "Displays high-fidelity HUD info above entities.");
        DESCRIPTIONS.put("Tracers",       "Draws lines from the crosshair to entities.");
        DESCRIPTIONS.put("Trigger",       "Attacks targets automatically when hovered.");
        DESCRIPTIONS.put("MaceSwap",      "Swaps to Mace automatically during falls.");
        DESCRIPTIONS.put("Hud",           "Configures screen overlays and HUD positions.");
        DESCRIPTIONS.put("Optimizer",     "Performs JVM and native RAM cleanups.");
        DESCRIPTIONS.put("NoWeb",         "Bypasses slow cobweb movement physics.");
        DESCRIPTIONS.put("Glint",         "Customizes item enchantment glow color.");
        DESCRIPTIONS.put("RichPresence",  "Displays RaveX status on Discord profile.");
        DESCRIPTIONS.put("GuiWalk",       "Allows moving around while inside menus.");
        DESCRIPTIONS.put("NoSlowDown",    "Prevents slowdown when eating or blocking.");
        DESCRIPTIONS.put("Velocity",      "Reduces or cancels incoming knockback.");
        DESCRIPTIONS.put("AutoEat",       "Eats food automatically when hunger is low.");
        DESCRIPTIONS.put("NoInteract",    "Prevents accidental block and container clicks.");
        DESCRIPTIONS.put("SourceFiller",  "Places sponges automatically to dry water.");
        DESCRIPTIONS.put("AirPlace",      "Places blocks in mid-air with visual guides.");
        DESCRIPTIONS.put("Scaffold",      "Places block bridges under player feet.");
        DESCRIPTIONS.put("Shaders",       "Applies static neon glowing effects to players.");
        DESCRIPTIONS.put("FreeLook",      "Enables 360 camera viewing without rotating.");
        DESCRIPTIONS.put("FreeCam",       "Detaches camera for spectator-mode flying.");
        DESCRIPTIONS.put("ViewClip",      "Allows third-person camera to pass through blocks.");
        DESCRIPTIONS.put("Step",          "Instantly ascends up full blocks like stairs.");
        DESCRIPTIONS.put("ReverseStep",   "Pulls you down to the ground instantly.");
        DESCRIPTIONS.put("Spammer",       "Spams text or file contents into chat.");
        DESCRIPTIONS.put("Commands",      "Enables control console for cheat commands.");
        DESCRIPTIONS.put("ItemPhysics",   "Gives realistic physical physics to dropped items.");
        DESCRIPTIONS.put("Sounds",        "Plays auditory effects on module actions.");
        DESCRIPTIONS.put("AntiHunger",     "Blocks hunger depletion completely.");
        DESCRIPTIONS.put("AutoSign",       "Fills signs with pre-configured text.");
        DESCRIPTIONS.put("AutoShear",      "Shears sheep in proximity automatically.");
        DESCRIPTIONS.put("AutoNameTag",    "Applies nametags to entities automatically.");
        DESCRIPTIONS.put("AutoMount",      "Mounts horses, pigs, or boats automatically.");
        DESCRIPTIONS.put("RideExploit",    "Rides any entity without saddles or reins.");
        DESCRIPTIONS.put("AntiVoid",       "Protects from void falls via teleport or bounce.");
        DESCRIPTIONS.put("AutoMend",       "Repairs armor automatically using XP bottles.");
        DESCRIPTIONS.put("FakePlayer",     "Spawns a client-side practice combat dummy.");
        DESCRIPTIONS.put("FastUse",        "Removes right-click placement delay limits.");
        DESCRIPTIONS.put("AutoRespawn",    "Respawns player instantly upon death.");
        DESCRIPTIONS.put("AutoArmor",     "Automatically equips the best armor.");
        DESCRIPTIONS.put("PacketLogger",   "Logs network TCP packets in game console.");
        DESCRIPTIONS.put("PacketCanceller","Blocks specific movement, chat, or attack packets.");
        DESCRIPTIONS.put("HandshakeSpoof", "Spoofs Lunar Client or custom server handshakes.");
        DESCRIPTIONS.put("LongJump",      "Performs long horizontal jumps with boosts.");
        DESCRIPTIONS.put("AutoLog",       "Disconnects from server during combat dangers.");
        DESCRIPTIONS.put("WebAura",       "Places cobwebs under target feet automatically.");
        DESCRIPTIONS.put("AutoWeapon",    "Swaps to the best damage weapon on attack.");
        DESCRIPTIONS.put("MaceAura",      "Deals massive fall damage with Mace instantly.");
        DESCRIPTIONS.put("Offhand",       "Puts Totems, Gapples, or Shields in second hand.");
        DESCRIPTIONS.put("MainHand",      "Puts selected combat items in primary hand.");
        DESCRIPTIONS.put("Hitboxes",      "Expands target collision bounding box sizes.");
        DESCRIPTIONS.put("Sleepy",        "Allows player to slide like on ice on any surface.");
        DESCRIPTIONS.put("Reach",         "Increases player block and entity interaction ranges.");
        DESCRIPTIONS.put("NoPush",        "Disables player physical pushing and rod pulling.");
        DESCRIPTIONS.put("FastBreak",     "Sets minimum break delay between block attacks.");
        DESCRIPTIONS.put("InstaBreak",    "Removes break delay entirely for instant breaking.");
        DESCRIPTIONS.put("GhostHand",     "Interacts with containers through walls.");
        DESCRIPTIONS.put("AutoSprint",    "Automatically sprints when moving forward.");
        DESCRIPTIONS.put("Spider",        "Climbs up walls like a spider while holding jump.");
        DESCRIPTIONS.put("Timer",         "Accelerates game tick rate for faster movement.");
        DESCRIPTIONS.put("Speed",         "Increases movement speed with various bypass modes.");
        DESCRIPTIONS.put("Xray",          "Makes blocks transparent and outlines chosen blocks.");
        DESCRIPTIONS.put("Surround",      "Places blocks around your feet for protection.");
        DESCRIPTIONS.put("BlockOutline",  "Customizable highlight on the targeted block.");
        DESCRIPTIONS.put("Fullbright",    "Makes everything fully bright.");
        DESCRIPTIONS.put("GuiParticles",  "Renders animated particles in ClickGUI.");
        DESCRIPTIONS.put("NoRotate",      "Prevents the server from rotating your head.");
        DESCRIPTIONS.put("NoRender",      "Disables rendering of specific client-side visuals like particles and fog.");
        DESCRIPTIONS.put("AutoWalk",      "Automatically walks forward.");
        DESCRIPTIONS.put("MobOwner",      "Displays the owner of tamed mobs.");
        DESCRIPTIONS.put("SelfTrap",      "Automatically places blocks around yourself.");
        DESCRIPTIONS.put("WaxAura",       "Automatically waxes nearby copper blocks.");
        DESCRIPTIONS.put("ChestAura",      "Automatically places chests around the player or entities.");
        DESCRIPTIONS.put("PortalGui",      "Use inventory and chat inside portals.");
        DESCRIPTIONS.put("Avoid",          "Avoids damaging blocks like cacti and berries.");
        DESCRIPTIONS.put("ItemScroller",   "Ctrl+Shift+Throw to mass-drop matching items. RShift+Scroll/LMB to transfer.");
        DESCRIPTIONS.put("ExtraTab",       "Some chest utility.");
        DESCRIPTIONS.put("ExtraChat",      "Some chat utility.");
        DESCRIPTIONS.put("ExtraChest",     "Some chest utility.");
        DESCRIPTIONS.put("AutoReconnect",  "Adds Reconnect button to Game Menu & Disconnect screen.");
        DESCRIPTIONS.put("FastLatency",    "Measures ping more frequently for accurate RTT.");
        DESCRIPTIONS.put("MultiTask",      "Allows attacking & mining while eating/using items.");
        DESCRIPTIONS.put("BlockSelector",  "Selects a random block from the hotbar after placing one.");
        DESCRIPTIONS.put("AutoSoup",       "Auto-drinks healing potions when health is low.");
        DESCRIPTIONS.put("NameProtect",    "Hides player name in nametags and chat (→RaveX).");
        DESCRIPTIONS.put("StashFinder",    "Detects & highlights stashes with valuable items.");
        DESCRIPTIONS.put("ClickTP",        "Right-click anywhere to instantly teleport there.");
        DESCRIPTIONS.put("ClickFly",       "Right-click a destination and fly toward it automatically.");
        DESCRIPTIONS.put("ChorusExploit",  "Eat chorus fruit to store teleport, press module keybind to trigger.");
        DESCRIPTIONS.put("TickShift",      "Store idle ticks and release them as speed bursts.");
        DESCRIPTIONS.put("TridentBoost",   "Boost your velocity when using a Riptide trident.");
        DESCRIPTIONS.put("WindAura",       "Auto-throws wind charges at nearby entities.");
        DESCRIPTIONS.put("BreadCrumbs",    "Draws trail lines behind you and other entities.");
        DESCRIPTIONS.put("ViewModel",      "Customize hand position, rotation and scale.");
        DESCRIPTIONS.put("AutoCrystal",    "Automatically places and breaks End Crystals for damage.");
        DESCRIPTIONS.put("Trap",           "Automatically boxes target players or entities using solid blocks.");
        DESCRIPTIONS.put("Igniter",        "Automatically ignites nearby TNT blocks.");
        DESCRIPTIONS.put("ExtraRocket",    "Multiplies elytra velocity when using firework rockets.");
        DESCRIPTIONS.put("ExtraRiding",    "Increases the speed of rideable entities.");
        DESCRIPTIONS.put("Blink",          "Cancels movement packets on enable, sends them on disable.");
        DESCRIPTIONS.put("PacketFly",      "Manipulates packets to fly through the air.");
        DESCRIPTIONS.put("AutoApple",      "Automatically eats golden apples under dangerous circumstances.");
        DESCRIPTIONS.put("TreeCutter",     "Automatically breaks nearby tree logs and renders 3D block highlights.");
        DESCRIPTIONS.put("FakePearl",     "Visually throws a client-side Ender Pearl without actual teleportation.");
        DESCRIPTIONS.put("BasePlace",     "Automatically places obsidian to optimize AutoCrystal damage to targets.");
        DESCRIPTIONS.put("AnchorAura",    "Intelligently places, charges, and explodes Respawn Anchors to damage targets.");
        DESCRIPTIONS.put("ElytraSwap",     "Swaps chestplate and elytra with customizable legitimacy modes.");
        DESCRIPTIONS.put("ElytraReplace",  "Replaces worn elytra with a fresh one from inventory at low durability.");
        DESCRIPTIONS.put("ViewLock",       "Prevents player client-side rotations entirely with Lua scripting support.");
        DESCRIPTIONS.put("ToolSaver",      "Prevents tools from breaking by swapping hotbar slots and canceling usages.");
        DESCRIPTIONS.put("AntiAim",        "Jitters or spins player head rotations silently or client-side.");
        DESCRIPTIONS.put("DesktopGui",     "Native desktop control.");
        DESCRIPTIONS.put("Breaker",        "Automatically mines protective blocks around targets to expose them to AutoCrystal explosions.");
        DESCRIPTIONS.put("BowAim",         "Automatically aims bows at target players or entities, predicting target movement and arrow trajectory.");
        DESCRIPTIONS.put("Quiver",         "Automatically shoots beneficial tipped arrows at the player to apply positive potion buffs.");
    }




    public static String getDescription(String moduleName) {
        return DESCRIPTIONS.getOrDefault(moduleName, "No description.");
    }
}
