set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32 /usr/lib/jvm/java-21-openjdk)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(JAVA_HOME /usr/lib/jvm/java-21-openjdk)
set(CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_MODULE_PATH})

set(JNI_FOUND TRUE CACHE BOOL "JNI found" FORCE)
set(JNI_INCLUDE_DIRS "${JAVA_HOME}/include;${CMAKE_CURRENT_LIST_DIR}" CACHE PATH "JNI include directories" FORCE)
set(JNI_LIBRARIES "" CACHE STRING "JNI libraries" FORCE)
